[sync] 2022/2/16
cfug/flutter.cn pull request #1032
Opened 2022-02-16 05:36 UTC by AlexV525

#374

2022-02-18 06:27 UTC, MeandNi requested changes

2022-02-18 06:27 UTC, MeandNi commented on src/cookbook/testing/integration/introduction.md
> +Next, use the `integration_test` and `flutter_test` packages
```suggestion
Next, use the `integration_test` and `flutter_test` packages
```

2022-02-19 10:26 UTC, AlexV525 commented on src/cookbook/testing/integration/introduction.md
> +Next, use the `integration_test` and `flutter_test` packages
```suggestion
Next, use the `integration_test` and `flutter_test` packages
```

2022-02-21 05:23 UTC, Vadaski commented on src/desktop/index.md
> +
此处是不是需要翻译一下？

2022-02-21 05:24 UTC, Vadaski commented on src/development/tools/devtools/cli.md
> +you can run the following command to launch DevTools:
此处需要翻译

2022-02-21 05:28 UTC, Vadaski reviewed
LGTM with nits

2022-02-21 07:22 UTC, Vadaski approved these changes
LGTM，辛苦 A 少～

2022-02-21 07:49 UTC, MeandNi approved these changes
LGTM

2022-02-21 07:55 UTC, merged