[sync] 2022/11/6
cfug/flutter.cn pull request #1239
Opened 2022-11-06 13:49 UTC by chenglu

ref #374 

好像最近没啥更新呀～

2022-11-06 16:33 UTC, Vadaski commented on src/development/data-and-backend/firebase.md
> +  [Flutter 插件页面][Firebase plugins]
Firebase 插件页面

2022-11-06 16:33 UTC, Vadaski requested changes
有一处小问题，其他都 LGTM 啦~

2022-11-07 04:54 UTC, chenglu commented on src/development/data-and-backend/firebase.md
> +  [Flutter 插件页面][Firebase plugins]
慧眼～ 哈哈

2022-11-07 05:02 UTC, chenglu commented
> 有一处小问题，其他都 LGTM 啦~

改好啦～ @Vadaski

2022-11-10 02:40 UTC, Vadaski approved these changes

2022-11-10 02:40 UTC, merged