[完成翻译]  get-started install 相关内容
cfug/flutter.cn pull request #725
Opened 2020-09-14 09:31 UTC by Vadaski

ref：#173

2020-09-14 09:42 UTC, cfug-dev requested changes
A little changes needed, thanks!

2020-09-14 09:42 UTC, cfug-dev commented on src/docs/get-started/install/_get-sdk-chromeos.md
> +    [更新您的路径][Update your path]。
这里指的是环境变量里的 path，所以路径一词不精确。

2020-09-14 09:42 UTC, cfug-dev commented on src/docs/get-started/install/_path-linux-chromeos.md
> +更多关于如何在 Bash 中配置环境变量的信息请查看[这条 StackExchange 提问][bash]。
```suggestion
更多关于如何在 Bash 中配置环境变量的信息请查看 [这条 StackExchange 提问][bash]。
```

2020-09-14 09:42 UTC, cfug-dev commented on src/docs/get-started/install/_path-linux-chromeos.md
> +更多关于如何在 Z shell 中配置环境变量的信息请查看[这条 StackExchange 提问][zsh]。
```suggestion
更多关于如何在 Z shell 中配置环境变量的信息请查看 [这条 StackExchange 提问][zsh]。
```

2020-09-15 00:38 UTC, cfug-dev approved these changes

2020-09-15 00:38 UTC, merged

2020-09-15 04:53 UTC, Vadaski commented on src/docs/get-started/install/_path-linux-chromeos.md
> +更多关于如何在 Bash 中配置环境变量的信息请查看[这条 StackExchange 提问][bash]。
中文之间我理解不加空格的呀～

2020-09-15 04:53 UTC, Vadaski commented on src/docs/get-started/install/_get-sdk-chromeos.md
> +    [更新您的路径][Update your path]。
了解，这里确实有些不准确