[完成翻译] Using the app size tool.
cfug/flutter.cn pull request #736
Opened 2020-10-20 02:36 UTC by CaiJingLong

在 issues 中没有找到对应任务。

2020-10-20 06:50 UTC, chenglu reviewed
我更新了一个小版本，主要是进行翻译格式的简单调整，包括如下：
- 中英文之间、超级链接后、代码引用前后加入了空格
- 简单统一了一下引号和括号的使用

以上，请指正。

技术内容请帮忙 @AlexV525 @Vadaski @Realank 三位老师看一下？

2020-10-20 09:57 UTC, AlexV525 requested changes
感谢翻译 有一些全局的修改已在标注中注明

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +[支配树](https://en.wikipedia.org/wiki/Dominator_(graph_theory)) 是可以立刻控制每一个子节点的树。
> 支配树是可以立刻控制每一个子节点的树。

支配树是一个树形结构的图表，
其子节点可以立刻被支配。

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +如果到“b”的每条路径都必须经过“A”，则节点“A”被称为“支配”节点“b”。
> 如果到“b”的每条路径都必须经过“A”，则节点“A”被称为“支配”节点“b”。

如果通往 `b` 的每条路径都必经节点 `a`，
那么我们可以说：节点 `a` 支配了节点 `b`。

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +把它放在应用程序大小分析的上下文中，想象一下`package:a` 导入了 `package:b` 和 `package:c`，
nit: 一下和 `package:a` 之间少了空格

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +把它放在应用程序大小分析的上下文中，想象一下`package:a` 导入了 `package:b` 和 `package:c`，
换行

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +这些信息有助于理解编译后的应用程序中出现某些代码片段的原因。
> 这些信息有助于理解编译后的应用程序中出现某些代码片段的原因。

这些信息对于您而言，可以帮助您理解编译后的应用程序中为何出现某些代码片段。

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +例如，如果您正在分析应用程序体积，并发现编译后的应用程序中包含意外的包，则可以使用支配树来跟踪包到其根源。
> 应用程序体积

应用程序的体积

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +例如，如果您正在分析应用程序体积，并发现编译后的应用程序中包含意外的包，则可以使用支配树来跟踪包到其根源。
换行

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +调用图提供了与支配树相似的信息，帮助您理解编译后的应用程序中存在代码的原因。
这一句参考上面的句子一起改下

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +不像支配树提供了一对多的节点体积数据, 调用图显示代码体积数据的节点之间存在的多对多关系。
> 不像支配树提供了一对多的节点体积数据, 调用图显示代码体积数据的节点之间存在的多对多关系。

它并不像支配数一样提供了一对多的代码体积数据节点，
而是展示了代码体积数据的节点之间存在的多对多关系。

@chenglu 这里可能需要再润一下

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +此数据的调用图将链接 `package：d` 直接调用者 `package：b` 以及 `package：c`，而不是它的『主宰者』 `package：a`.
> 此数据的调用图将链接 `package：d` 直接调用者 `package：b` 以及 `package：c`，而不是它的『主宰者』 `package：a`.

此数据的调用图会将直接调用者 `package:b` 和 `package:c` <— 这里留一个空格
与 `package:d` 链接在一起，
而不是它的「支配者」 `package:a`。

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +这些信息对于理解代码片段（包、库、类、函数）之间的细粒度依赖关系非常有用。
包、库、类和函数

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +#### 我应该使用支配树还是调用图?
全角问号

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +如果您想了解一段代码之间的所有调用路径，请使用调用图。
了解 -> 理解

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +支配树是调用图数据的分析或切片，其中节点通过『支配』而不是父子层次结构连接。
> 其中节点通过『支配』而不是父子层次结构连接

其中节点是通过「支配」而不是父子层级进行连接的

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +在调用图完成的情况下（每对节点之间存在一条边），支配树将显示 `root` 是图中每个节点的支配者。
将显示出

换行

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +## 差异标签
页/卡

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +diff 选项卡允许您比较体积信息的两个快照。
> diff 选项卡允许您比较体积信息的两个快照。

diff 标签页让您可以比较体积信息的两个快照。

![1603186419661](https://user-images.githubusercontent.com/15884415/96568353-6e80f080-12fa-11eb-803c-0e3dae0c8613.jpg)

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +您要比较的两个体积信息文件应该从同一个应用程序的两个不同版本生成，例如，在更改代码之前和之后生成的体积文件。
换行

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +您可以使用 treemap 和 table 可视化两个数据集之间的差异。
这为啥不翻译呢？ 😄

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +当您打开 Diff 选项卡时，您将看到加载「旧」和「新」大小文件的说明。
直角引号

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +当您打开 Diff 选项卡时，您将看到加载「旧」和「新」大小文件的说明。
参考上文中对于 instruction 翻译的意见

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +要使用尺寸体积工具，您需要生成一个 flutter 体积分析文件。
尺寸体积？ 🤣

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +此文件包含整个应用程序的大小信息（本机代码、Dart 代码、assets 资源、字体等），
这里和27行一样

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +您可以使用`--analyze size`标志生成它：
nit: 代码和文字之间缺少空格

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +这会构建你的应用并输出尺寸的摘要到命令行，然后告诉你在哪里找到体积分析文件。
然后 -> 同时

换行

2020-10-20 09:57 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +在这个示例中，更进一步导入 `build/apk-code-size-analysis_01.json` 文件到体积分析工具。
> 在这个示例中，更进一步导入 `build/apk-code-size-analysis_01.json` 文件到体积分析工具。

在这个示例中，想要进行更进一步的分析，
请导入 `build/apk-code-size-analysis_01.json` 文件到体积分析工具。

2020-10-20 11:54 UTC, CaiJingLong commented on src/docs/development/tools/devtools/app-size.md
> +## 分析标签
这个可以商榷, 因为其实我们都知道指的是对应 tab 里的内容。
但是作为标题来说, 感觉「页」字加不加都怪怪的。

先按照你review的意见来。

2020-10-20 12:01 UTC, CaiJingLong commented on src/docs/development/tools/devtools/app-size.md
> +每个矩形的面积与节点在编译后的应用程序中所占的大小成比例。
这里从中文语义来说是一样的。
「面积和大小成比例」
「面积和大小成比例关系」

2020-10-20 12:16 UTC, CaiJingLong commented on src/docs/development/tools/devtools/app-size.md
> +您可以使用 treemap 和 table 可视化两个数据集之间的差异。
开始到这里的时候觉得这两个词可能是开发者工具上的文字，不翻译会比较容易让开发者更容易找到对应的选项卡。

到了后面这部分的详细翻译的时候才发现可能翻译了也没问题，但是前面的就忘了

2020-10-20 12:21 UTC, CaiJingLong commented on src/docs/development/tools/devtools/app-size.md
> +要使用尺寸体积工具，您需要生成一个 flutter 体积分析文件。
可能是脑抽了

2020-10-20 13:50 UTC, AlexV525 requested changes
Almost done! Just two nit picking left.

2020-10-20 13:50 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +如果 DevTools 未连接到应用，您可以从启动 DevTools 后出现的登录页访问该工具(查看 [安装说明][installation instructions])。
括号部分换行，另外括号要全角

2020-10-20 13:50 UTC, AlexV525 commented on src/docs/development/tools/devtools/app-size.md
> +diff 选项卡让您可以比较体积信息的两个快照。
选项卡 和 标签页 统一为一个？标签页？

2020-10-21 02:17 UTC, AlexV525 approved these changes
![image](https://user-images.githubusercontent.com/15884415/96665025-8e5df600-1386-11eb-9e86-a72b3036f71d.png)

2020-10-21 02:17 UTC, AlexV525 commented
Thanks for contributing!

2020-10-21 02:17 UTC, merged