[完成翻译] ios app clip
cfug/flutter.cn pull request #737
Opened 2020-10-20 07:39 UTC by CaiJingLong

2020-10-21 08:49 UTC, CaiJingLong commented
自查完成
- 修复了格式的问题
- 调整了部分翻译的措辞

2020-10-23 03:33 UTC, CaiJingLong commented
App Clip target、App Clip 这两个词在本篇文章中通篇未做翻译，保持了原样
这里个人感觉 App Clip 不翻译为佳， target 则可翻译可不翻译，如 reviewer 觉得应该翻译，我可以做整体修改

2020-10-23 03:36 UTC, CaiJingLong commented
翻译中 `add-to-app` 这个词保持了原样。
因为这个东西让我感觉很类似于 [create-react-app](https://github.com/facebook/create-react-app) 的感觉，而 `create-react-app` 在各种 react 文档中均保持了原样，所以我个人倾向于这么做。

2020-11-02 10:25 UTC, AlexV525 requested changes

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +  这个支持在 Flutter 1.22 版本中是试验性功能, 可能不稳定, 也许在未来会修改。
```suggestion
  这个支持在 Flutter 1.22 版本中是实验性功能, 可能不稳定, 也许在未来会修改。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +并将它到您现有的 Flutter 项目或 [add-to-app][] 项目。
```suggestion
并将它集成到您现有的 Flutter 项目或 [add-to-app][] 项目。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +  需要具有 CocoaPods 1.10.0.beta.1 或更高版本
```suggestion
  CocoaPods 需要 1.10.0.beta.1 或更高版本
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +要查看一个示例，请参阅 GitHub 上的 [App Clip 示例][App Clip sample]。
```suggestion
要查看完整可用的示例，请参阅 GitHub 上的 [App Clip 示例][App Clip sample]。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +打开您的 iOS Xcode 工程, 例如您的完整 Flutter 项目中的 `ios/Runner.xcworkspace`
```suggestion
打开您的 iOS Xcode 工程，例如您的纯 Flutter 项目中的 `ios/Runner.xcworkspace`。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +为新的 target 激活(activate)一个新的 scheme。
```suggestion
为新的 target 激活 (activate) 一个新的 scheme。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +在项目浏览器的新创建的 App Clip 组中，
上文未翻译 Project Navigator，这里建议也不翻

```suggestion
在项目 Project Navigator 的新创建的 App Clip 组中，
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +删除除 `Info.plist` 和 `App Clip target.entitlements` 之外的所有内容。
```suggestion
将除了 `Info.plist` 和 `App Clip target.entitlements` 以外的所有内容删除。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +如果您不使用 `SceneDelegate.swift` 文件,
这里应该不用换行，而且下方多了一个空格

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +删除 `Application Scene Manifest` 字典。
```suggestion
删除 `Application Scene Manifest` 字典条目。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +## 步骤4 共享构建配置
```suggestion
## 步骤 4 -  共享构建配置
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +如果您是 Objective-C 还应该包括 `Supporting Files/main.m`，
```suggestion
（如果您是 Objective-C 还应该包括 `Supporting Files/main.m`）
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +还应该在 `Target Membership` 选中 `App Clip`。
```suggestion
并且在 `Target Membership` 选中 `App Clip`。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +## 步骤 6 - 添加 App Clip 的 关联域
```suggestion
## 步骤 6 - 添加 App Clip 的关联域名
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +添加 `Associated Domains` 数组类型。
```suggestion
添加 `Associated Domains` 数组。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +  需要 CocoaPods 的版本为 1.10.0.beta.1 或更高才可以运行 Flutter 插件。
参考上文相同修改点

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +或是 add-to-app 的 host 项目中打开 `Podfile` 文件。
```suggestion
或是 add-to-app 的宿主项目中打开 `Podfile` 文件。
```

2020-11-02 10:25 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +要从一开始测试启动一个 App Clip，也可以查看苹果公司的文档
```suggestion
要从头测试 App Clip 的启动，您也可以查看苹果公司的文档
```

2020-11-03 00:41 UTC, CaiJingLong commented on src/docs/development/platform-integration/ios-app-clip.md
> +  需要具有 CocoaPods 1.10.0.beta.1 或更高版本
这里我觉得需要斟酌，从主谓宾的角度来说，你的建议 Cocoapod 变成了主语，似乎是Cocoapod需要XXX，
而实际上，是使用者需要Cocoapod的更高版本

2020-11-03 00:44 UTC, CaiJingLong commented on src/docs/development/platform-integration/ios-app-clip.md
> +如果您是 Objective-C 还应该包括 `Supporting Files/main.m`，
这里按照你的建议修改，但我觉得不加括号可能从中文的角度来说语义更明确

2020-11-03 01:42 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +  需要具有 CocoaPods 1.10.0.beta.1 或更高版本
在这里我的理解是带有插件的 Flutter App 实际上是 Cocoapods 去运行的，通常我们两种主语模式都会说，例如：
* 你需要 Flutter SDK 在 1.22 版本以上，才能在 iOS 14 上 进行 debug。
* Flutter SDK 需要 1.22 版本才能让你在 iOS 14 上 debug。

两种角度而言，我觉得都正确，只是在这里我认为第二种更好，毕竟实际承载运行的是 Cocoapods 本身

FYI @chenglu

2020-11-03 03:15 UTC, CaiJingLong commented on src/docs/development/platform-integration/ios-app-clip.md
> +  需要具有 CocoaPods 1.10.0.beta.1 或更高版本
这里其实是要结合上下文的

目前我的翻译是： 需要具有 CocoaPods 1.10.0.beta.1 或更高版本才能运行带有插件的 Flutter 应用程序。

你的建议修改是：CocoaPods 需要 1.10.0.beta.1 或更高版本才能运行带有插件的 Flutter 应用程序。

完整的主语变成了 Cocoapod， 从中文的角度来说，肯定是不合适的

当然我之前的翻译可能也是缺少主语的，这里应该还需要再斟酌一下

2020-11-03 03:16 UTC, AlexV525 commented on src/docs/development/platform-integration/ios-app-clip.md
> +  需要具有 CocoaPods 1.10.0.beta.1 或更高版本
所以改成有主语的也可以，上面举的例子中，第一种就是现有的翻译，但是译文里是缺了主语的

2020-11-03 07:28 UTC, CaiJingLong commented on src/docs/development/platform-integration/ios-app-clip.md
> +  需要具有 CocoaPods 1.10.0.beta.1 或更高版本
动词开头是隐式主语，比如在一篇文章说：
打开文件 xxx ，然后删除xxx

不需要特别的写： 你打开文件 xxx，删除 xxx 是一个意思

![image](https://user-images.githubusercontent.com/14145407/97958830-04337a00-1de9-11eb-9f55-dad04af45ad5.png)
类似于这种，就不需要写：“你“下载什么，而是直接说下载xxx，这样更符合中文的习惯。 

很多地方

2020-11-03 10:34 UTC, AlexV525 approved these changes

2020-11-03 10:35 UTC, merged