[完成翻译] dart:ffi.
cfug/flutter.cn pull request #739
Opened 2020-10-20 08:55 UTC by CaiJingLong

2020-10-21 03:58 UTC, CaiJingLong commented
二次自查完，
- [x] 整理中英文格式和符号。
- [x] 修改一些不通顺的翻译

2020-10-22 10:33 UTC, AlexV525 requested changes

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +并修改 CMakeLists.txt 文件。
缺少代码块

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +FFI 库只能与 C 符号绑定，因此在 C++ 中，
一般可以在句号 或者语义上有截断的时候再进行换行

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +还应该添加属性来指示符号是从 Dart 引用的，
同时，这些符号需要添加一些属性，用来表明它们是从 Dart 引用的，

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +路径为： `ios/Classes/native_add.cpp`。
代码块和标点之间 一般不需要空格

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +在项目的根目录命令行中执行：
在项目的根目录下执行以下命令：

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +    添加 C/C++/Objective-C/Swift 源码文件到 XCode 工程中。
Xcode

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +你需要创建一个 `CMakeLists.txt` 文件去定义应该如何编译源文件，
去定义应该如何 -> ，用来定义如何

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +然后还要告诉 Gradle 如何去定位它们。
然后还要告诉 -> 同时告诉

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +## 步骤 3： 在 FFI 库中读取代码
nit: Extra space

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +但是，Dart 绑定代码的位置并不重要。
但是，Dart 在何处进行代码绑定并不重要。

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +但在 iOS 上它使用插件的名称。
但在 iOS 上，它将使用...

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +使用库的的句柄，你可以解析 `native_add` 符号：
您可以通过使用库的句柄来解析 `native_add` 符号：

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +(`example/lib/main.dart`)中演示它。
全角括号

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +但目前还不清楚苹果的审查程序如何处理这一问题。
但目前仍然不确定苹果的审查程序将如何处理两者的使用。

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +可以使用 [`DynamicLibrary.executable`][] 或 [`DynamicLibrary.process`][].
上下两句调换

```
您可以使用 [`DynamicLibrary.executable`][] 或 [`DynamicLibrary.process`][]
解析静态链接到应用程序二进制文件的符号。
```

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +   选择 target 设备。
选择目标设备

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +2. Select the target platform.
序号以原文为准 可能影响到后续文档更新

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +    将以下前缀添加到导出的符号声明中，以确保它们对 Dart 可见
缺少冒号

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +2. Add the framework file to the **Embedded Binaries**
序号同上

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +   如果存在签名正确的 `Framework` 文件，请打开 `Runner.xcworkspace`。
签名正确 -> 已进行签名

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +      拖动你的预编译的 `libyourlibrary.dylib` 到你的 `Runner/Frameworks`。
拖动您已经预编译的

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
>  ---
GLOBAL:
* 你 -> 您
* 处理空格、大小写、全半角符号
* `_xxx_` 和 `*xxx*` 统一为 `**xxx**`

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +         拖动 `libyourlibrary.dylib` 到 `Copy Bundle Resources` 列表.
句号

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +要添加一个闭源的库到 [Flutter macOS 桌面][Flutter macOS Desktop] 应用
缺少逗号

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +要创建一个包含 C/C++/Objective-C _and_ Dart
内容未翻译完整

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +请查看以下使用说明：
统一 use the following instructions 的翻译口径

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +而是应该从可信的第三方下载此插件，
相反，应该从可信的第三方下载此插件。

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +    在 Android 文档的 [Android NDK Native api][] 列表中找到所需的库。它列出了稳定的本地 API。
英文内容不匹配

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +遵循安卓文档中的 [添加C和C++代码到项目][Add C and C++ code to your project]
C C++ 缺少空格

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +要创建包含 Dart 源代码
逗号

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +要创建包含 Dart 源代码
逗号

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +   添加 aar 工件作为依赖。
将 AAR 工件添加为依赖。

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +   **不要**在你的 flutter package 中导入工件。
大小写

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +   对应的，它需要在一个仓库中下载，比如 Jcenter。
大小写

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +因为这样实际上可以节省设备空间。
这样 -> 这种做法

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +共享对象可以直接从APK加载，
空格

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +APK是在传输过程中额外打包的 -
空格

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +这导致 APK 体积更小，但在设备体积上更大。
这会

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +Flutter apk 文件默认情况下不遵循这些指导原则
大小写

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +当创建一个 release 档案(IPA)时，符号会被 Xcode 删除。
全角括号

2020-10-22 10:33 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +   从 **All Symbols** 修改为 **Non-Global Symbols**。
从 -> 将

2020-10-23 00:50 UTC, CaiJingLong commented on src/docs/development/platform-integration/c-interop.md
> +在Android上，动态链接库作为一组 `.so`(ELF) 文件分发，
额外解释可能不必，毕竟展开需要很多篇幅
我觉得可以考虑通过添加[维基百科](https://zh.wikipedia.org/wiki/%E5%8F%AF%E5%9F%B7%E8%A1%8C%E8%88%87%E5%8F%AF%E9%8F%88%E6%8E%A5%E6%A0%BC%E5%BC%8F)链接的方式来介绍
或：
使用 [ELF标准文档](https://refspecs.linuxbase.org/elf/elf.pdf)，虽然会通读原文的人基本不会有 :)

2020-10-23 00:57 UTC, CaiJingLong commented on src/docs/development/platform-integration/c-interop.md
> +还应该添加属性来指示符号是从 Dart 引用的，
这里我虽然反复读过，但总感觉原文表述的意思怪怪的，和实际感觉不符。

我个人觉得应该是添加属性来告诉编译器，这是dart中需要的，而不是这个是从dart引入的

2020-10-23 01:04 UTC, CaiJingLong commented on src/docs/development/platform-integration/c-interop.md
> +(`example/lib/main.dart`)中演示它。
不是说纯英文用英文括号吗

2020-10-23 01:09 UTC, CaiJingLong commented on src/docs/development/platform-integration/c-interop.md
> +2. Select the target platform.
我的vscode插件在我回车的时候自动换了， 没注意到

2020-10-23 01:20 UTC, CaiJingLong commented on src/docs/development/platform-integration/c-interop.md
> +请查看以下使用说明：
后面的部分因为原文格式很一致，保持相同是应该的。
前面有两处强行保持一致感觉对于中文来说不合理。

2020-10-23 01:35 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +在Android上，动态链接库作为一组 `.so`(ELF) 文件分发，
那就：ELF（可执行与可链接格式）

2020-10-23 01:43 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +还应该添加属性来指示符号是从 Dart 引用的，
有道理，如果我们把句子拆开：to indicate...are refereced, from Dart 是不是能理解了？

2020-10-23 02:07 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +请查看以下使用说明：
统一在句末的单独句即可

2020-10-23 02:21 UTC, CaiJingLong commented on src/docs/development/platform-integration/c-interop.md
> +还应该添加属性来指示符号是从 Dart 引用的，
还应该添加属性来表明符号是需要被 Dart 引用的，

2020-10-23 02:23 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +还应该添加属性来指示符号是从 Dart 引用的，
> 还应该添加属性来表明符号是需要被 Dart 引用的，

同时，这些符号需要添加一些属性，用来表明它们需要被 Dart 引用的，

2020-10-23 02:30 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +(`example/lib/main.dart`)中演示它。
咨询了 @chenglu 这里就保持现状吧

2020-10-23 03:16 UTC, CaiJingLong commented on src/docs/development/platform-integration/c-interop.md
> +在Android上，动态链接库作为一组 `.so`(ELF) 文件分发，
这里括号套括号感觉怪怪的，有什么额外的建议？

2020-10-23 03:16 UTC, CaiJingLong commented on src/docs/development/platform-integration/c-interop.md
> +在Android上，动态链接库作为一组 `.so`(ELF) 文件分发，
在 Android 上，动态链接库作为一组 `.so`（ELF（可执行与可链接格式））文件分发，

2020-10-23 06:56 UTC, AlexV525 requested changes

2020-10-23 06:56 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +**FFI** 代表[**外部功能接口**][FFI]。
```suggestion
**FFI** 代表 [**外部功能接口**][FFI]。
```

2020-10-23 06:56 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +
```suggestion
相比之下，动态链接库则分布在应用程序中的单独的文件或文件夹中，
并按需加载。
在 Android 上，动态链接库作为一组 `.so`（[ELF（可执行与可链接格式）][]）文件分发，
每个架构各有一个。
在 iOS 上，它是作为 `.framework` 文件夹分发的。

[ELF（可执行与可链接格式）]: https://zh.wikipedia.org/wiki/%E5%8F%AF%E5%9F%B7%E8%A1%8C%E8%88%87%E5%8F%AF%E9%8F%88%E6%8E%A5%E6%A0%BC%E5%BC%8F
```

2020-10-23 06:56 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +[Dart Api][Dart API reference documentation].
```suggestion
[Dart API][Dart API reference documentation].
```

2020-10-23 06:56 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +2. Select the target platform.
还是没有替换回来噢

2020-10-23 06:56 UTC, AlexV525 commented on src/docs/development/platform-integration/c-interop.md
> +要创建一个包含 C/C++/Objective-C **and** Dart 代码的 Flutter 插件，
```suggestion
要创建一个包含 C/C++/Objective-C **和** Dart 代码的 Flutter 插件，
```

2020-10-23 07:20 UTC, AlexV525 commented
> 这篇文章在侧边导航里的标题怪怪的，原文是 "C and C++ interop", 我觉得英文和实际语义都应该表达的是dart和c/c++的互操作性， 但是这个中文翻译感觉像是再说 c 和 c++ 间的互操作性一样

可以带着一起改下，我个人觉得也是

2020-10-23 07:32 UTC, AlexV525 approved these changes

2020-10-23 07:33 UTC, merged

2020-10-23 08:25 UTC, chenglu commented on src/_data/sidenav.yml
> +        - title: C/C++ 代码集成及调用
or 翻译成：与 C 和 C++ 互调？
@AlexV525 @CaiJingLong

2020-10-23 08:42 UTC, AlexV525 commented on src/_data/sidenav.yml
> +        - title: C/C++ 代码集成及调用
本篇的内容目前还没有涉及到反向调用dart 所以感觉现在这个合适些