[完成翻译] Platform views
cfug/flutter.cn pull request #740
Opened 2020-10-21 03:13 UTC by CaiJingLong

2020-10-21 04:00 UTC, CaiJingLong commented
本篇的格式的自查完成。

2020-10-25 05:04 UTC, AlexV525 requested changes

2020-10-25 05:04 UTC, AlexV525 commented on src/docs/development/platform-integration/platform-views.md
> +当在 Dart 中实现了 `build()` 方法，你可以使用 [`defaultTargetPlatform`][]
```suggestion
在 Dart 中实现 `build()` 方法时，您可以使用 [`defaultTargetPlatform`][] 
```

2020-10-25 05:04 UTC, AlexV525 commented on src/docs/development/platform-integration/platform-views.md
> +来检测当前的平台，并且决定如何使用这个 Widget：
```suggestion
来检测当前的平台，并且决定如何使用这个 widget：
```

2020-10-25 05:04 UTC, AlexV525 commented on src/docs/development/platform-integration/platform-views.md
> +由于此复制每帧发生一次，因此可能会影响整个 Flutter UI 的性能。
```suggestion
由于每帧都会进行一次复制，因此可能会影响整个 Flutter UI 的性能。
```

2020-10-25 05:04 UTC, AlexV525 commented on src/docs/development/platform-integration/platform-views.md
> +对于复杂的情况，可以使用一些技术来缓解这些问题。
```suggestion
对于复杂的情况，可以使用一些技巧来缓解这些问题。
```

2020-10-25 05:04 UTC, AlexV525 commented on src/docs/development/platform-integration/platform-views.md
> +请考虑拍摄本地视图的屏幕快照并将其渲染为纹理。
```suggestion
请考虑对原生视图进行截图，并将其渲染为纹理。
```

2020-10-27 07:09 UTC, CaiJingLong commented on src/docs/development/platform-integration/platform-views.md
> +翻译为平台视图总感觉怪怪的，而且在本文中容易和 Native views 混淆，
新的写法中我只在标题和开始的介绍中使用「集成平台视图」这个说法，
后面使用「平台视图」这个显得不那么啰嗦的说法。

2020-10-27 07:09 UTC, CaiJingLong commented on src/docs/development/platform-integration/platform-views.md
> +对于在应用中注册，修改应用中的 `AppDelegate.swift`：
已处理

2020-10-27 07:31 UTC, AlexV525 approved these changes
LGTM modulo comments below

2020-10-27 07:31 UTC, AlexV525 commented on src/docs/development/platform-integration/platform-views.md
> +在工厂类和平台视图的头文件中添加。
```suggestion
在工厂类和平台视图的文件头部添加以下内容。
```

2020-10-27 07:31 UTC, AlexV525 commented on src/docs/development/platform-integration/platform-views.md
> +为了在 Flutter 中使用平台视图，所以性能有所折衷。
```suggestion
在 Flutter 中使用平台视图时，性能会有所折衷。
```

2020-10-27 07:31 UTC, AlexV525 commented on src/docs/development/platform-integration/platform-views.md
> +另一方面，Virtual display 使平台视图的每个像素
```suggestion
另一方面，虚拟显示模式使平台视图的每个像素
```

2020-10-28 03:10 UTC, merged