[完成翻译] implicit-animations
cfug/flutter.cn pull request #742
Opened 2020-10-28 01:58 UTC by toly1994328

2020-10-28 03:56 UTC, chenglu commented on src/docs/codelabs/implicit-animations.md
>  <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfTcB884FuPXukPEEewU5pgphZyF2Ue0pOWoIHvRp-4D-xYjw/viewform?embedded=true" width="100%" height="1726" frameborder="0" marginheight="0" marginwidth
```suggestion
<iframe src="https://g.forms.cn/forms/d/e/1FAIpQLSfTcB884FuPXukPEEewU5pgphZyF2Ue0pOWoIHvRp-4D-xYjw/viewform?embedded=true" width="100%" height="1726" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
```

2020-10-28 03:59 UTC, chenglu commented on src/docs/codelabs/implicit-animations.md
>  <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfTcB884FuPXukPEEewU5pgphZyF2Ue0pOWoIHvRp-4D-xYjw/viewform?embedded=true" width="100%" height="1726" frameborder="0" marginheight="0" marginwidth
刚刚把这个链接加入了白名单，可以通过 g.forms.cn 访问了。

2020-10-28 03:59 UTC, chenglu commented on src/docs/codelabs/implicit-animations.md
> +  当属性们改变使用提供的`curve`和`duration`时，渐变动画会自动在新旧属性值之间进行动画。
```suggestion
  当属性们改变使用提供的 `curve` 和 `duration` 时，渐变动画会自动在新旧属性值之间进行动画。
```

2020-10-28 03:59 UTC, chenglu commented on src/docs/codelabs/implicit-animations.md
> +  当属性们改变使用提供的`curve`和`duration`时，渐变动画会自动在新旧属性值之间进行动画。
建议在代码和中文之间加入空格。

2020-10-28 04:00 UTC, chenglu commented on src/docs/codelabs/implicit-animations.md
>  {{site.alert.secondary}}
```suggestion
{{site.alert.secondary}}

```

2020-10-28 04:01 UTC, chenglu commented on src/docs/codelabs/implicit-animations.md
>  {{site.alert.secondary}}
目前已知了一个小 bug 就是需要在这个下面加入一个换行，否则中英文显示不奏效 ;-)

2020-10-28 04:01 UTC, chenglu commented on src/docs/codelabs/implicit-animations.md
> +前面的示例展示了：如何让你通过渐变动画对特定的 widget 属性值进行动画变化，以及如何通过`duration` 参数设置动画完成所需的时间。渐变动画还允许你在 `duration` 时长内控制动画的__速率__变化。用来定义这种速率变化的参数是 [curve][curve]。
```suggestion
前面的示例展示了：如何让你通过渐变动画对特定的 widget 属性值进行动画变化，以及如何通过 `duration` 参数设置动画完成所需的时间。渐变动画还允许你在 `duration` 时长内控制动画的__速率__变化。用来定义这种速率变化的参数是 [curve][curve]。
```

2020-10-28 04:01 UTC, chenglu commented on src/docs/codelabs/implicit-animations.md
> +该codelab包括以下内容:
```suggestion
该 codelab 包括以下内容:
```

2020-10-28 04:02 UTC, chenglu requested changes
格式上有一些小问题我已经提出啦。

2020-10-29 08:00 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +  当属性们改变使用提供的 `curve` 和 `duration` 时，渐变动画会自动在新旧属性值之间进行动画。
```suggestion
  渐变动画会在新旧属性值变换时，自动使用提供的 `curve` 和 `duration` 进行动画变换。
```

2020-10-29 08:01 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +  如果你不指定 `curve`，渐变动画默认会使用 [线性曲线][linear curve]。
```suggestion
  如果您没有指定 `curve`，隐式动画的曲线会默认使用 [线性曲线][linear curve]。
```

2020-10-29 08:01 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +
多余的空行

2020-10-30 02:33 UTC, AlexV525 requested changes

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +  这些步骤概述了如何使用`AnimatedOpacity` widget 来添加以下的动画特性：
```suggestion
  这些步骤概述了如何使用 `AnimatedOpacity` widget 来添加以下的动画特性：
```

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +  一个有`margin`、`borderRadius`、和 `color` 属性的 `Container`，
```suggestion
  一个有 `margin`、`borderRadius`、和 `color` 属性的 `Container`，
```

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +都由一个相关的函数赋值（ 分别是 `randomColor()`、
```suggestion
都由一个相关的函数赋值
```

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +`randomBorderRadius()` 和 `randomMargin()`）。
```suggestion
（分别是 `randomColor()`、`randomBorderRadius()` 和 `randomMargin()`）。 
```

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +
多余的空行

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +  查看[形状变化初始代码][shape-shifting starter code] 里修改的位置。
```suggestion
  查看 [形状变化初始代码][shape-shifting starter code] 里修改的位置。
```

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +`change()` 方法可以使用`setState()` 为 `color`、`borderRadius` 和 `margin` 状态变量设置新值：
```suggestion
`change()` 方法可以使用 `setState()` 为
`color`、`borderRadius` 和 `margin` 状态变量设置新值：
```

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +然后当您将常量 [easeInOutBack][easeInOutBack] 传递给 `curve` 时，
```suggestion
然后当您将常量 [easeInOutBack][] 传递给 `curve` 时，
```

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +注意：`margin`、`borderRadius` 和 `color` 的变化速率遵循 `easeInOutBack` 所定义的曲线:
因为超80了，所以根据语义换行

```suggestion
注意：`margin`、`borderRadius` 和 `color` 的变化速率
遵循 `easeInOutBack` 所定义的曲线:
```

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +[形状变化完成代码][shape-shifting complete] 示例对 `margin`、`borderRadius` 和 `color` 属性值进行了动画变换。
换行

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +这个 [形状变化完成代码][shape-shifting complete] 的示例建立在 [渐变完成代码][fade-in complete] 的基础上，
换行

2020-10-30 02:33 UTC, AlexV525 commented on src/docs/codelabs/implicit-animations.md
> +  学习 [hero动画][hero animations] 和 [staggered动画][staggered animations]。
```suggestion
  学习 [hero 动画][hero animations] 和 [staggered 动画][staggered animations]。
```

2020-10-30 05:51 UTC, AlexV525 approved these changes
LGTM 感谢修正

2020-11-02 04:22 UTC, chenglu approved these changes
Agreed w/ @AlexV525's review suggestions.
LGTM +1

2020-11-02 04:32 UTC, merged