[完成翻译] desktop
cfug/flutter.cn pull request #750
Opened 2020-11-16 00:32 UTC by toly1994328

Resolves #692

2020-11-16 06:22 UTC, MeandNi reviewed
review+1，感谢 @toly1994328 翻译👍

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +重设备的下拉选项中，选择 **windows (desktop)**、
重 --> 从

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +然后运行您的应用，会看到它在桌面启动。
```suggestion
然后运行您的应用，就会看到应用在桌面启动。
```

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +
```suggestion
要创建一个包含桌面支持的新应用
（除了移动支持），运行下面的命令，
需要将 `myapp` 替换成您项目的名称：
```

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +
感觉 “为了” 可以改成 “要”，下同，建议。

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +授予特定的权限或者服务，比如下面：
```suggestion
授予特定的权限或者服务，比如：
```

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +
这一部分好像有一段没翻译😄

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +有关这个主题的更多信息，
建议将这里的 主题 —--> 话题

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +也可以下载并检查源代码，以了解
检查 --> 阅读

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +
这一部分缺少最后一句话

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +
缺少一部分翻译

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +  您总是可以使用不带参数的 `flutter config`
```suggestion
  您之后可以使用不带参数的 `flutter config` 
```

2020-11-16 06:22 UTC, MeandNi commented on src/desktop.md
> +您可能也要运行 `flutter doctor` 来查看
```suggestion
您也可以运行 `flutter doctor` 来查看
```

2020-11-16 07:12 UTC, toly1994328 commented on src/desktop.md
> +
哈哈，还真看漏了...

2020-11-16 08:23 UTC, AlexV525 requested changes
- 译文在实际操作中不需要扣字眼，只要不与原意产生偏差+信雅达即可
- 格式需要按照 wiki 进一步调整
- 换行有点多了

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +使用当前构建进行测试。
> 然而，这里有一些信息，关于如何在其他机器上使用当前构建进行测试。

不过，这里还有一些内容，可以帮助您在其他机器上使用当前构建进行测试。

不要过于拘泥原文的句式和词语，信雅达是第一标准。

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +  从相同的目录
冒号

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +  所示的任何方法。
```suggestion
  所示的任何方法进行发布。
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +关于向 [Snap Store][] 发布 Linux 应用的信息，
```suggestion
有关向 [Snap Store][] 发布 Linux 应用，
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +请参见[构建发布一个Linux桌面程序]
```suggestion
请参见 [构建发布一个Linux桌面程序][Build and release a Linux desktop app]
```

这里换行换的有点离谱了

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +[Build and release a Linux desktop app]。
```suggestion

```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +随着工具的完善，请继续关注发布 Linux
```suggestion
这些工具将不断进行完善，欢迎您持续关注 Linux 桌面应用的其他方式的更新信息。
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +来管理权限文夹，请注意，
```suggestion
来管理权限文件，请注意
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +在 [App Store][] 上发布应用，这是必需的。）
```suggestion
在 [App Store][] 上发布应用，这是必需的），
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +例如，没有 `com.apple.security.network.client`
```suggestion
假设您没有设置 `com.apple.security.network.client` 
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +权限，网络请求将会失败，并显示如下消息:
```suggestion
权限，网络请求将会失败，并显示如下消息：
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +如果您选择在 App Store 之外
```suggestion
如果您选择在 App Store 以外的地方
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +### Hardened runtime
如果无需翻译 可以不加

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +比如，Windows 实现的`url_launcher`，
```suggestion
比如，Windows 实现的 `url_launcher`，
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +：这个 codelab 会引导您通过使用 Flutter，
https://github.com/cfug/flutter.cn/wiki/Translation-Spec#%E7%89%B9%E5%88%AB%E6%B3%A8%E6%84%8F

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +来构建一个集成 GitHub GraphQL API 桌面应用。
```suggestion
来构建一个集成 GitHub GraphQL API 的桌面应用。
```

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +Flutter Gallery [运行 web 应用]
这一段的格式有问题 需要调整下

2020-11-16 08:23 UTC, AlexV525 commented on src/desktop.md
> +[图片搜索应用][Photo Search app]：
同上

2020-11-16 08:43 UTC, toly1994328 commented on src/desktop.md
> +使用当前构建进行测试。
nice

2020-11-16 16:24 UTC, AlexV525 requested changes

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +如果您在使用的 Linux 发行版上无法使用 snapd，您可以使用下面的命令行:
```suggestion
如果您在使用的 Linux 发行版上无法使用 `snapd`，您可以使用下面的命令行:
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +您应该会看到如下的内容（您将看到 Windows、macOS 或 Linux，
```suggestion
您应该会看到如下的内容（您将看到 Windows、macOS 或 Linux，取决于您启用的是哪个平台）：
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +#### IDE
同样的内容可以不用翻

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +**macOS (desktop)**、或 **linux (desktop)**
```suggestion
**macOS (desktop)** 或 **linux (desktop)** 
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +#### Windows
同上

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +#### macOS
同上

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +#### Linux
同上

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +## 具体的 macOS 支持
```suggestion
## 针对 macOS 的支持
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +这些链接列出了**所有**的包，不仅是插件包。
```suggestion
这些链接列出了 **所有** 的包，不仅是插件包。
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +（记住这点，**插件包**或**插件**提供了一个平台特定的服务接口。）
```suggestion
（记住这点，**插件包** 或 **插件** 提供了一个平台特定的服务接口。）
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +### 写一个插件
```suggestion
### 编写一个插件
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +  [开发包和插件][Developing packages and plugins] 特别是 [联合插件][] 部分。
```suggestion
  [开发包和插件][Developing packages and plugins]，特别是 [联合插件][] 部分。
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +[写一个 Flutter 桌面程序][Write a Flutter desktop application]：
```suggestion
[写一个 Flutter 桌面程序][Write a Flutter desktop application]
```

2020-11-16 16:24 UTC, AlexV525 commented on src/desktop.md
> +Gallery 的构成部分有：Material design widgets 的集合、
从这行开始 需要保持缩进

2020-11-17 06:00 UTC, AlexV525 approved these changes
![LGTM](https://user-images.githubusercontent.com/15884415/99352198-23e49b00-28dd-11eb-9c9e-439622a950ce.png)

@chenglu 需要确认一下 <br> 的格式

2020-11-17 06:19 UTC, MeandNi commented
LGTM

2020-11-17 07:03 UTC, merged