src/docs/resources/architectural-overview.md
cfug/flutter.cn pull request #815
Opened 2021-02-08 15:58 UTC by AlexV525

Resolves #779 .

2021-03-29 15:57 UTC, MeandNi reviewed
这篇文章翻译起来确实晦涩，感谢 A 少。（10%）

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +组件们无法越权访问更底层的内容，并且它们每一个都是可选且可替代的。
```suggestion
Flutter 被设计为一个可扩展的分层系统。
它可以被看作是各个独立的组件的系列合集，上层组件各自依赖下层组件。
组件无法越权访问更底层的内容，并且框架层中的各个部分都是可选且可替代的。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +对于底层操作系统而言，Flutter 应用程序的包装方式与其他原生应用相同。
```suggestion
对于底层操作系统而言，Flutter 应用程序的打包方式与其他原生应用相同。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +从而提供一个程序入口，程序由此可以与底层操作系统进行协调，
分层这一栏，`embedder ` 翻译为 `嵌入层` 感觉更好。
```suggestion
在每一个平台上，都会包含一个具备平台特性的嵌入层，
其会提供一个程序入口，程序由此可以与底层操作系统协调交互，
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +嵌入构建由平台适用的编程语言编写，当前 Android 使用的是 Java 和 C++，
```suggestion
嵌入层由平台适用的编程语言编写，如 Android 使用的是 Java 和 C++，
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +Flutter 代码可以通过这些嵌入构建，以模块方式集成到现有的应用中，或是成为应用的全部内容。
```suggestion
Flutter 代码可以通过嵌入层，以模块方式集成到现有的应用中，或是成为应用的全部内容。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +[存在一些其他的构建][other embedders also exist]。
```suggestion
Flutter 本身包含了常见的各个平台嵌入层，同时也
[存在一些其他的构建][other embedders also exist]。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +该库暴露了最底层的原语，包括驱动输入、图形、和文本渲染的子系统的类。
```suggestion
该库暴露了最底层的原语，包括用于驱动输入、图形、和文本渲染的子系统的类。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +总的来说，它有以下的内容：
```suggestion
通常，开发者可以通过 **Flutter 框架层** 与 Flutter 交互，
该框架提供了以 Dart 语言编写的现代响应式框架。
它包括由一系列层组成的一组丰富的平台，布局和基础库。从下层到上层，依次有：
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +  提供了底层基础内容的常用抽象。
```suggestion
  基础的 **[foundational]({{site.api}}/flutter/foundation/foundation-library.html)**
  类及一些基层之上的构建块服务，如 **[animation]({{site.api}}/flutter/animation/animation-library.html)、
  [painting]({{site.api}}/flutter/painting/painting-library.html) 和
  [gestures]({{site.api}}/flutter/gestures/gestures-library.html)**，
  他们可以提供上层常用的抽象。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +  提供了操作布局的抽象。有了渲染层，你可以构建以树状结构组织的可渲染对象。
```suggestion
  用于提供操作布局的抽象。有了渲染层，你可以构建以树状结构组织的可渲染对象。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +，其中囊括了对传统架构设计的挑战。
```suggestion
，其中包含了对传统设计理念的再度解构。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +在其被定义后，会根据代码在运行时单独更新，并与事件进行交互。
```suggestion
在大部分传统的 UI 框架中，界面的初始状态通常会被一次性定义，
然后，在运行时根据用户代码分别响应事件进行更新。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +开发者将数据的改动通过控制器推至模型，模型再将新的状态通过控制器推至界面。
```suggestion
开发者将数据的改动通过控制器（Controller）推至模型（Model），
模型再将新的状态通过控制器推至界面（View）。
```

2021-03-29 15:57 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +从设计角度来看，它应该是快速且没有其他影响的。
```suggestion
`build()` 方法在框架需要时都可以被调用（每个渲染帧可能会调用一次），
从设计角度来看，它应当能够快速执行且无害的。
```

2021-03-30 01:52 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +又或是 Web 平台的 JavaScript，Flutter 应用都将直接编译成机器码。
这里个人认为还是保留原来的版本，读者更容易理解。
```suggestion
而对于发行版 (release) 而言，无论是英特尔的 x64 还是 ARM 指令集，
又或是 Web 平台的 JavaScript，Flutter 应用都将直接编译成机器码。
```

2021-03-30 02:04 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +嵌入构建由平台适用的编程语言编写，当前 Android 使用的是 Java 和 C++，
这里 embedder 个人认为可以翻译为嵌入层。
```suggestion
该嵌入层采用了适合当前平台的语言编写，例如 Android 使用的是 Java 和 C++，
```

2021-03-30 02:08 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +对于底层操作系统而言，Flutter 应用程序的包装方式与其他原生应用相同。
我看到这里和打包貌似有点区别，再考虑一下？

2021-03-30 02:12 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +从而提供一个程序入口，程序由此可以与底层操作系统进行协调，
其实我一开始想翻译为「嵌入器」，我个人认为它不像一个层级结构，而是单一的集成入口。不过从层级角度来说「嵌入层」也有道理。

2021-03-30 02:14 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +Flutter 代码可以通过这些嵌入构建，以模块方式集成到现有的应用中，或是成为应用的全部内容。
```suggestion
Flutter 代码可以通过嵌入层，以模块方式集成到现有的应用中，也可以作为应用的主体。
```

2021-03-30 02:24 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +从设计角度来看，它应该是快速且没有其他影响的。
「无害」感觉不太对劲，我重新调整了一下。

```suggestion
`build()` 方法在框架需要时都可以被调用（每个渲染帧可能会调用一次），
从设计角度来看，它应当能够快速执行且没有额外影响的。
```

2021-03-30 02:24 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +从设计角度来看，它应该是快速且没有其他影响的。
「无害」感觉不太对劲，我重新调整了一下。

```suggestion
`build()` 方法在框架需要时都可以被调用（每个渲染帧可能会调用一次），
从设计角度来看，它应当能够快速执行且没有额外影响的。
```

2021-03-30 02:26 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +总的来说，它有以下的内容：
```suggestion
自下而上，依次包括：
```

2021-03-30 05:51 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +然后反序列化为 Kotlin（例如 `HashMap`）或者 Swift（例如 `Dictionary`）的等效类型表示。
这个直接是不是错别字？
```suggestion
Dart 和平台组件（例如由 Kotlin 或 Swift 代码编写）之间发送和接收消息。
数据会由 Dart 类型（例如 Map）序列化为一种标准格式，
然后反序列化为 Kotlin（例如 `HashMap`）或者 Swift（例如 `Dictionary`）中的等效类型。 
```

2021-03-30 05:51 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +实际上，Dart 的运行时提供了在 Dart 对象的堆上分配内存，以及调用静态或动态链接库的能力。
```suggestion
实际上，Dart 的运行时提供了在堆上分配 Dart 对象内存的支持，以及调用静态或动态链接库的能力。
```

2021-03-30 05:51 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +  响应接触测试和手势，将其转换为等效的原生输入事件。
```suggestion
  响应命中测试和输入手势，将其转换为等效的原生输入事件。
```

2021-03-30 05:51 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +因此该方法通常更适合复杂的控件，例如谷歌地图，在 Flutter 中重新实现是不可行的。
```suggestion
因此该方法通常更适合复杂的控件，例如谷歌地图这种不适合在 Flutter 中重新实现的。
```

2021-03-30 05:51 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +为了将展示 Flutter 内容的任何界面上的延迟降到最小，
```suggestion
为了将任意 Flutter 界面上的延迟降到最小，
```

2021-03-30 05:51 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +另外，将 Flutter 引擎进行分离，可以在多个 Flutter 页面上进行复用，共享加载了必需的库的内存。
```suggestion
另外，Flutter 的引擎分离使得多个 Flutter 页面可以复用引擎，共享必要库加载时的内存消耗。
```

2021-03-30 05:51 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +由于 Flutter 框架是 Dart 编写的，将其编译成 JavaScript 相对而言更为直截了当。
这里个人觉得翻译为简单就可以了。
```suggestion
由于 Flutter 框架是 Dart 编写的，将其编译成 JavaScript 相对而言更为简单。
```

2021-03-30 05:51 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +大部分开发者绝对写不出碰到这种差异问题的代码。
```suggestion
大部分开发者将永远不会碰到编写这种差异代码的情况。
```

2021-03-30 05:54 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +对于底层操作系统而言，Flutter 应用程序的包装方式与其他原生应用相同。
是不是可以翻译为封装？

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +[`Center`]({{site.api}}/flutter/widgets/Center-class.html) widget 内。
```suggestion
类的层次结构是有意的浅而广，以最大限度地增加可能的组合数量，
重点放在小的、可组合的 widget 上，确保每个 widget 都能很好地完成一件事情。
核心功能均被抽象，甚至像边距和对齐这样的基础功能，都被实现为单独的组件，而不是内置于核心中。
（这样的实现也与传统的 API 形成了对比，类似边距这样的功能通常都内置在了每个组件的公共核心内，
Flutter 中的 widget 则不同。）因此，如果你需要将一个 widget 居中，
与其调整 `Align` 这样的属性，不如将它包裹在一个
[`Center`]({{site.api}}/flutter/widgets/Center-class.html) widget 内。
```

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +其他的 widget 可以以对无状态和有状态的 widget 进行同样的处理，同时不需要担心丢失状态。
```suggestion
其他的 widget 可以对无状态和有状态的 widget 进行同样的处理，同时不需要担心丢失状态。
```

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +与其他类相同，你可以通过构造来为 widget 初始化它的数据，
构造函数？

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +调用 `of(context)` 会获取构建的上下文（当前 widget 位置的句柄），
```suggestion
调用 `of(context)` 会根据当前构建的上下文（即当前 widget 位置的句柄），
```

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +Flutter 的分层架构还支持使用其他实现来替换状态至 UI 的方案，例如
```suggestion
Flutter 的分层架构也允许使用其他实现来替换状态至 UI 的方案，例如
```

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +它包含了从 widget 结构转换成屏幕上绘制的实际像素的一系列步骤。
```suggestion
包括 widget 结构转换成屏幕上绘制的实际像素的一系列步骤。
```

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +Flutter 还包含了以这种组合方法组成的实用型 widgets。
这里的  `padding, alignment, rows, columns, and grids` 是否需要保留。
```suggestion
Flutter 中包含了边距、对齐、行、列和网格系列的 widgets。
这些布局类型的 widgets 并自身没有视觉内容，
而只用于控制其他 widgets 的部分布局条件。
Flutter 也包含了以这种组合方法组成的实用型 widgets。
```

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +该 widget 将一个共用的祖先节点包裹在 widget 树中，如下面的例子所示：
```suggestion
然而，随着 widget 树层级逐渐加深，依赖树形结构上下传递状态信息会变得十分麻烦。
这时，第三种类型的 widget&mdash;&mdash;
[`InheritedWidget`]({{site.api}}/flutter/widgets/InheritedWidget-class.html)，
提供了一种从共同的祖先节点获取数据的简易方法。
你可以使用 `InheritedWidget` 创建包含状态的 widget，
该 widget 会将一个共同的祖先节点包裹在 widget 树中，如下面的例子所示：
```

2021-03-30 14:55 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +现在当 `ExamWidget` 或 `GradeWidget` 对象需要获取 `StudentState` 的数据时，
```suggestion
现在，当 `ExamWidget` 或 `GradeWidget` 对象需要获取 `StudentState` 的数据时，
```

2021-03-30 15:24 UTC, Nayuta-D commented on src/docs/resources/architectural-overview.md
>  JavaScript if targeting the web. The framework is open source, with a permissive
这儿是不是漏了一句：Flutter 的框架代码是开源的，遵循 BSD 开源协议，并拥有蓬勃发展的第三方库生态来补充核心库功能。

2021-03-30 15:31 UTC, Nayuta-D commented on src/docs/resources/architectural-overview.md
> +   **平台嵌入构建** 的概览：让 Flutter 应用可以在移动端及桌面端操作系统执行的代码。
感觉一般都是说 平台嵌入层

2021-03-30 17:27 UTC, Nayuta-D reviewed
这么大的翻译量，辛苦了，文章质量特别高。

2021-03-30 17:27 UTC, Nayuta-D commented on src/docs/resources/architectural-overview.md
> +在这之后，子节点会 **将大小以从下到上的方式** 传递给它们的父节点对象已经建立关联的限制。
```suggestion
子节点若要确定自己的大小，则 **必须** 遵循父节点传递的限制。
子节点的响应方式是在父节点建立的约束内 **将大小以从下到上的方式** 传递给父节点。
```

2021-03-30 17:27 UTC, Nayuta-D commented on src/docs/resources/architectural-overview.md
> +嵌入构建同时负责管理应用的生命周期，包括输入的操作（例如鼠标、键盘和触控），
```suggestion
嵌入构建同时负责管理应用的生命周期，包括输入的操作（例如鼠标、键盘和触控）、
```

2021-03-30 17:29 UTC, Nayuta-D commented on src/docs/resources/architectural-overview.md
> +从上至下都是这样的结构，如下面的示例所示：
文章还有多处是 从上而下 ， 如果要修改可以注意下

2021-03-30 17:30 UTC, Nayuta-D commented on src/docs/resources/architectural-overview.md
> +   **平台嵌入构建** 的概览：让 Flutter 应用可以在移动端及桌面端操作系统执行的代码。
后面还有好几个地方是 平台嵌入构建 ，如果要修改也需注意

2021-03-31 02:15 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +Widgets 通常由更小的且用途单一的 widgets 组合而成，它们可以通过互相加持来产生更大的效果。
```suggestion
Widgets 通常由更小的且用途单一的 widgets 组合而成，提供更强大的功能。
```

2021-03-31 02:20 UTC, yumi0629 commented on src/docs/resources/architectural-overview.md
> +来表示屏幕上的绘制、布局（定位及大小）、用户交互、状态管理、主题、动画及导航。
感觉这里就是“位置和大小”的意思吧，“定位及确定大小”是不是会有点冗余？

2021-03-31 02:29 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +大部分开发者绝对写不出碰到这种差异问题的代码。
个人认为这里的原意是，同样的代码会出现效果的差异，而不是自己手写出来的

2021-03-31 03:56 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +又或是 Web 平台的 JavaScript，Flutter 应用都将直接编译成机器码。
> 这里个人认为还是保留原来的版本，读者更容易理解。

主要原文意义并非原来的版本，JavaScript 不是机器码。

2021-04-02 15:26 UTC, MeandNi requested changes

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +Element 树每一帧之间都是持久化的，因此它扮演着重要的角色，
```suggestion
Element 树每一帧之间都是持久化的，因此起着至关重要的性能作用，
```

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +仅仅是判断发生变化的 widget，Flutter 就可以重建需要重新配置的 Element 树的部分。
Just a suggestion.
```suggestion
Flutter 依靠该优势，实现了一种好似 widget 树被完全抛弃，而缓存了底层表示的机制。
仅仅是判断发生变化的 widget，Flutter 就可以重建需要重新配置的 Element 树的部分。
```

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +只绘制单个 widget 的应用极其稀有。
```suggestion
很少有应用只绘制单个 widget。
```

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +这样的设计让 `RenderObject` 拥有高效的抽象能力，处理各种各样的使用场景。
```suggestion
这样的设计让 `RenderObject` 拥有高效的抽象能力，能够处理各种各样的使用场景。
```

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +这是再平凡不过的事情：它并不总是一个固定的大小，甚至不符合笛卡尔坐标规律
```suggestion
这是再平凡不过的事情：它并不总是一个固定的大小，甚至不遵循笛卡尔坐标规律
```

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +`RenderObject` 继承的 `RenderObjectElement`。
```suggestion
在构建阶段，Flutter 会为 Element 树中的每个 `RenderObjectElement` 创建
或更新其对应的一个从 `RenderObject` 继承的对象。
```

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +  父节点可以通过设定最大和最小的尺寸限制，将子节点对象的大小调整为相同的值。
```suggestion
  父节点可以通过设定最大和最小的尺寸限制，决定其子字节对象的大小。
```

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +更多有关限制和布局系统的信息，以及可参考的例子，可以在
```suggestion
更多有关约束和布局系统的信息，及可参考的例子，可以在
```

2021-04-02 15:26 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +子节点可以检查从上层传递下来的限制，并利用该限制决定如何使用，例如下方的使用方法：
```suggestion
这样的盒子约束模型，同样也适用于子节点对象需要知道有多少可用空间渲染其内容的场景，
通过使用 [`LayoutBuilder`]({{site.api}}/flutter/widgets/LayoutBuilder-class.html) widget，
子节点可以得到从上层传递下来的约束，并酌情使用该约束对象，使用方法如下：
```

2021-04-03 04:49 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +`StatefulWidget` 没有 build 方法，对于它而言，build 方法在其对应的 `State` 对象中。
我感觉不成，因为 `build()` 是 widget 特有的方法，这里又突出了 stful 的 build 在它的 State 里

2021-04-03 04:49 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +来告知框架，再次调用 `State` 的 build 方法来更新 UI。
这里可以译

2021-04-03 04:54 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +子节点可以检查从上层传递下来的限制，并利用该限制决定如何使用，例如下方的使用方法：
这里倒不是酌情使用了，意思更接近 **如何利用父级的限制布局**。

2021-04-04 06:32 UTC, MeandNi requested changes

2021-04-04 06:32 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +所以在 Flutter 的内部不存在类似 Android 视图或由 Flutter 内部渲染的 widget。
```suggestion
因此在 Flutter 的内部模型中无法存在 Android 视图之类的内容，也无法与 Flutter 的 widget 交错渲染
```

2021-04-04 06:32 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +在上层应用中托管 Flutter 内容
```suggestion
### 在上层应用中托管 Flutter 内容
```

2021-04-04 06:32 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +Flutter 模块的模板是为了易于集成而设计的。
```suggestion
Flutter 模块模板设计简单，易于嵌入。
```

2021-04-04 06:32 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +另外，Flutter 的引擎分离使得多个 Flutter 页面可以复用引擎，共享必要库加载时的内存消耗。
```suggestion
Flutter 引擎需要一段短暂的时间做初始化，用于加载 Flutter 的共享库、初始化 Dart 的运行时、
创建并运行 Dart isolate 线程并将渲染层与 UI 进行绑定。
为了最大限度地减少呈现 Flutter 界面时的延迟，
最好是在应用初始化时或至少在第一个 Flutter 页面展示前，一并初始化 Flutter 引擎，
如此一来用户不会在首个 Flutter 页面加载时感到突然地卡顿。
另外，Flutter 的引擎分离使得多个 Flutter 页面可以复用引擎，共享必要库加载时的内存消耗。
```

2021-04-04 06:32 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +只要 JavaScript 存在，Dart 就会将产物编译成 JavaScript，并且优化可以用于开发和生产的工具链。
```suggestion
Dart 语言存在之初就已经支持直接编译成 JavaScript，并且针对开发和生产目的对其工具链进行了优化。
```

2021-04-04 06:32 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +而在 WebGL 模式下，Flutter 使用了一个编译为 WebAssembly 版本的 Skia，
```suggestion
而在 WebGL 模式下，Flutter 使用了一个编译为 WebAssembly 的 Skia 版本，
```

2021-04-04 06:32 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +大部分开发者绝对写不出碰到这种差异问题的代码。
```suggestion
大部分开发者绝对可以无差异地编写这两种模式下的代码。
```

2021-04-04 06:32 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +  父节点可以通过设定最大和最小的尺寸限制，决定其子字节对象的大小。
```suggestion
  父节点可以通过设定最大和最小的尺寸限制，决定其子节点对象的大小。
```

2021-04-04 06:39 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +子节点可以检查从上层传递下来的限制，并利用该限制决定如何使用，例如下方的使用方法：
> 这里倒不是酌情使用了，意思更接近 **如何利用父级的限制布局**。

edited.

2021-04-04 06:39 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +`StatefulWidget` 没有 build 方法，对于它而言，build 方法在其对应的 `State` 对象中。
> 我感觉不成，因为 `build()` 是 widget 特有的方法，这里又突出了 stful 的 build 在它的 State 里

edited.

2021-04-04 06:39 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +对于底层操作系统而言，Flutter 应用程序的包装方式与其他原生应用相同。
> 我看到这里和打包貌似有点区别，再考虑一下？

还想到已经好的表述方式，可以保留。

2021-04-04 11:19 UTC, MeandNi approved these changes
This LGTM with a minor nit.

2021-04-04 11:19 UTC, MeandNi commented on src/docs/resources/architectural-overview.md
> +Flutter 框架相对较小，因为一些开发者可能会使用到的更高层级的功能，
```suggestion
Flutter 框架相对较小，因为一些开发者可能会使用到的更高层级的功能
```

2021-04-04 13:57 UTC, Nayuta-D commented on src/docs/resources/architectural-overview.md
> +而后，我们会对讲述 widgets 如何被组织，并转换成应用程序的渲染对象。
```suggestion
而后，我们会讲述 widgets 如何被组织，并转换成应用程序的渲染对象。
```

2021-04-04 15:00 UTC, CaiJingLong reviewed
我觉得一些翻译还需要斟酌， 我添加了一些个人建议

2021-04-04 20:40 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +（Intel x64 或 ARM 指令集），或者针对 Web 平台的 JavaScript。
下面加上了

2021-04-04 20:45 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +Flutter 的框架代码是开源的，遵循 BSD 开源协议，并拥有蓬勃发展的第三方库生态来补充核心库功能。
```suggestion
Flutter 的框架代码是开源的，遵循 BSD 开源协议，并拥有蓬勃发展的第三方库生态来补充核心库功能。

```

2021-04-04 20:45 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +，开发者负责提供应用状态与界面状态之间的映射，框架则在运行时将应用状态的更改更新到界面上。
```suggestion
[一个响应式的且伪声明式的 UI 框架](/docs/resources/faq#what-programming-paradigm-does-flutters-framework-use)，
开发者负责提供应用状态与界面状态之间的映射，框架则在运行时将应用状态的更改更新到界面上。
```

2021-04-04 20:45 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +或是调用 C 语言基础的 API，或是将原生代码能力嵌入 Flutter 应用，
这里的句式应该是类似 the first thing, the second thing, and the third thing 的连续用法。
accessing... , calling... , embedding... , or embedding...

2021-04-04 20:51 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +Dart 和平台组件（例如由 Kotlin 或 Swift 代码编写）之间发送和接收消息。
```suggestion
通过创建一个常用的通道（封装通道名称和编码），开发者可以在
Dart 与使用 Kotlin 和 Swift 等语言编写的平台组件之间发送和接收消息。
```

2021-04-06 05:19 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +[Facebook 自己的 React 框架](https://www.youtube.com/watch?time_continue=2&v=x7cQ3mrcKaY&feature=emb_logo)
```suggestion
[Facebook 自己的 React 框架]({{site.youtube-site}}/watch?time_continue=2&v=x7cQ3mrcKaY&feature=emb_logo)
```

2021-04-06 05:19 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +[关于 Flutter 渲染流程的讨论](https://www.youtube.com/watch?v=UUfXWzp0-DU)
```suggestion
[关于 Flutter 渲染流程的讨论]({{site.youtube-site}}/watch?v=UUfXWzp0-DU)
```

2021-04-06 05:21 UTC, AlexV525 commented on src/docs/resources/architectural-overview.md
> +来表示屏幕上的绘制、布局（定位及确定大小）、用户交互、状态管理、主题、动画及导航。
```suggestion
来表示屏幕上的绘制、布局（位置和大小）、用户交互、状态管理、主题、动画及导航。
```

2021-04-10 09:14 UTC, AlexV525 commented
感谢各位参与 review~即将进行合并

2021-04-10 09:17 UTC, merged