[sync] 2021/2/19
cfug/flutter.cn pull request #822
Opened 2021-02-19 11:09 UTC by chenglu

ref #374 

new file:   src/docs/get-started/codelab_migrated.md
new file:   src/docs/cookbook/effects/expandable-fab.md

2021-02-19 11:29 UTC, Vadaski requested changes
辛苦啦，还有几处小细节待讨论～

2021-02-19 11:29 UTC, Vadaski commented on src/desktop.md
> +[将 app 提交至 Mac App Store][CHS distribute your app via the macOS App Store]，
这里链接与原文不一致，待讨论～

2021-02-19 11:29 UTC, Vadaski commented on src/desktop.md
>  这将会在您的 Flutter 桌面项目中添加必要的已有文件和文件夹。
这里译文需补齐

2021-02-19 11:29 UTC, Vadaski commented on src/docs/development/packages-and-plugins/using-packages.md
> +查看 [Flutter Favorites 项目][Flutter Favorites program] 页面。
「Flutter Favorites 项目」 译为 「最受欢迎的 Flutter 项目」怎么样～待议

2021-02-19 11:48 UTC, chenglu commented on src/docs/development/packages-and-plugins/using-packages.md
> +查看 [Flutter Favorites 项目][Flutter Favorites program] 页面。
广告法⚠️

2021-02-19 14:53 UTC, Vadaski commented on src/docs/development/packages-and-plugins/using-packages.md
> +查看 [Flutter Favorites 项目][Flutter Favorites program] 页面。
了解 哈哈哈

2021-02-19 17:18 UTC, chenglu commented on src/desktop.md
> +或 [将 app 提交至 Mac App Store][CHS distribute your app via the macOS App Store]。
搞定。

2021-02-20 15:05 UTC, AlexV525 commented on src/_includes/null-safe-recipe.md
> +{{site.alert.note}}
```suggestion
{{site.alert.note}}

```

2021-02-20 15:05 UTC, AlexV525 commented on src/_includes/null-safe-recipe.md
> +{{site.alert.end}}
```suggestion

  该代码片段启用了空安全。
  空安全目前已于 beta 渠道的 Dart 语言和 Flutter 框架发布。
  您可在 [Flutter 中的空安全](/docs/null-safety) 了解更多信息。

{{site.alert.end}}
```

2021-02-20 15:06 UTC, AlexV525 approved these changes

2021-02-21 17:11 UTC, merged