[sync] 2021/04/17
cfug/flutter.cn pull request #850
Opened 2021-04-16 10:51 UTC by Vadaski

暂无更新文章

2021-04-17 05:48 UTC, AlexV525 requested changes

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/cookbook/navigation/passing-data.md
> +Pass the arguments as part of the [`RouteSettings`][].
下面也要补一下，我点不到

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/development/tools/web-renderers.md
> +## 配置运行时
```suggestion

## 配置运行时
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/development/tools/web-renderers.md
> +  使用 auto 选项构建应用
```suggestion
  使用 auto 选项构建应用。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/development/tools/web-renderers.md
> +无法在 `main.dart.js` 启动 Flutter engine 之后更换 web 渲染器。
```suggestion
Flutter engine 启动之后无法再在 `main.dart.js` 更换 web 渲染器。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/get-started/codelab-web.md
> +**Web服务器**将启动托管该应用程序的服务器以便您可以从任何浏览器加载它。
```suggestion
**Web服务器** 将启动托管该应用程序的服务器，以便你可以从任何浏览器加载它。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/get-started/codelab.md
> +  **提示：如果你已经 [启用 web][enabled web]，你的应用可以在这里面的所有设备上运行。
```suggestion
  **提示：如果你已经 [启用 web][enabled web]，你的应用可以在这里面的所有设备上运行。**
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/get-started/codelab.md
> +以及 [编写你的第一个 Flutter web 应用程式][codelab-web]。
```suggestion
以及 [编写你的第一个 Flutter web 应用程序][codelab-web]。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +`Zone` 仅会打印错误，而不会执行其他任何操作。
```suggestion
它们由发生区域的 `Zone` 处理。
`Zone` 在默认情况下仅会打印错误，而不会执行其他任何操作。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +下面的每一种错误捕获类型都解释了。
```suggestion
下面解释了所有的错误捕获类型。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +在底部的代码段可以处理所有类型的错误。
```suggestion
在最后的代码段可以用于处理所有类型的错误。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +先了解每种错误类型。
```suggestion
尽管你可以直接复制粘贴代码段，但我们建议你先了解每种错误类型。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +## Flutter 导致的错误
```suggestion

## Flutter 导致的错误 
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
>  可以使用下面的回调方法:
```suggestion
例如，如果你想在 release 模式下发生错误时立刻关闭应用，
可以使用下面的回调方法:
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +## 定义一个自定义的 error widget 以构建错误阶段
```suggestion
## 自定义一个 ErrorWidget 以展示 build 时的错误
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +For example:
```suggestion
## Errors not caught by Flutter

## 未被 Flutter 捕获的错误

Consider an `onPressed` callback that invokes an asynchronous function,
such as `MethodChannel.invokeMethod` (or pretty much any plugin).
For example:

假设一个 `onPressed` 回调调用了异步方法，例如 `MethodChannel.invokeMethod`
（或者其他 plugin 的方法）：
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +To catch such an error, use [`runZonedGuarded`][].
```suggestion
If `invokeMethod` throws an error, it won't be forwarded to `FlutterError.onError`.
Instead, it's forwarded to the `Zone` where `runApp` was run.

如果 `invokeMethod` 抛出了错误，它不会传递至 `FlutterError.onError`，
而是直接进入 `runApp` 的 `Zone`。

To catch such an error, use [`runZonedGuarded`][].

如果你想捕获这样的错误，请使用 [`runZonedGuarded`][]。
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +
```suggestion

请注意，如果你的应用在 `runApp` 中调用了
`WidgetsFlutterBinding.ensureInitialized()` 方法来进行一些初始化操作
（例如 `Firebase.initializeApp()`），则必须在 `runZonedGuarded` 中调用
`WidgetsFlutterBinding.ensureInitialized()`：
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +    was called from the outside.
```suggestion

    Error handling wouldn't work if `WidgetsFlutterBinding.ensureInitialized()`
    was called from the outside.

    如果 `WidgetsFlutterBinding.ensureInitialized()` 在外部调用，
    错误将不会被捕获到。

```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +## Handling all types of errors
```suggestion
## Handling all types of errors

## 处理所有类型的错误
```

2021-04-17 05:48 UTC, AlexV525 commented on src/docs/testing/errors.md
> +your errors handling on next code snippet:
```suggestion
Say you want to exit application on any exception and to display
a custom error widget whenever a widget building fails - you can base
your errors handling on next code snippet:

如果你想在异常抛出时退出应用，并在 build 错误时展示自定义的 ErrorWidget，
你可以在下面的代码片段的基础上定制你的处理：
```

2021-04-21 06:37 UTC, Vadaski commented
收到，我今晚来改

2021-04-23 07:09 UTC, chenglu commented on src/docs/cookbook/effects/typing-indicator.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:10 UTC, chenglu commented on src/docs/cookbook/effects/staggered-menu-animation.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:10 UTC, chenglu commented on src/docs/cookbook/effects/shimmer-loading.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:10 UTC, chenglu commented on src/docs/cookbook/effects/photo-filter-carousel.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:10 UTC, chenglu commented on src/docs/cookbook/effects/parallax-scrolling.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:10 UTC, chenglu commented on src/docs/cookbook/effects/nested-nav.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:10 UTC, chenglu commented on src/docs/cookbook/effects/gradient-bubbles.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:10 UTC, chenglu commented on src/docs/cookbook/effects/drag-a-widget.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:11 UTC, chenglu commented on src/docs/cookbook/effects/download-button.md
>      url: https://dartpad.dev/inject_embed.dart.js
```suggestion
    url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-23 07:11 UTC, chenglu commented on src/docs/codelabs/layout-basics.md
> +  url: https://dartpad.dev/inject_embed.dart.js
```suggestion
  url: https://dartpad.cn/inject_embed.dart.js
```

2021-04-24 15:07 UTC, AlexV525 approved these changes

2021-04-24 15:17 UTC, merged