[翻译完成] src/docs/development/ui/animations/implicit-animations.md
cfug/flutter.cn pull request #868
Opened 2021-05-11 10:14 UTC by scvoet

[翻译完成] implicit-animations.md
Resolves #584

2021-05-12 02:13 UTC, AlexV525 requested changes
文章中有较多的全局格式需要调整，参考：
* https://github.com/cfug/flutter.cn/wiki/%E6%96%87%E6%A1%A3%E7%BF%BB%E8%AF%91%E6%A0%BC%E5%BC%8F-(Translation-Spec) 
* https://github.com/cfug/flutter.cn/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%88%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97-(Chinese-Typography-Guide)

2021-05-12 02:13 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +: 跳转至代码！
https://github.com/cfug/flutter.cn/wiki/%E6%96%87%E6%A1%A3%E7%BF%BB%E8%AF%91%E6%A0%BC%E5%BC%8F-(Translation-Spec)#%E7%89%B9%E5%88%AB%E6%B3%A8%E6%84%8F 。下同。

```suggestion
<br>跳转至代码！
```

2021-05-12 02:13 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +聚焦 Flutter 视频以 5 到 10 分钟的实战代码为特点，涵盖了每个 Flutter 开发人员都需要从头到尾了解的技术。
不太通顺，可以优化一下。

2021-05-12 02:13 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +## 无聊秀
cc @chenglu @Vadaski @MeandNi

2021-05-12 02:13 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> -
需要回滚。

2021-05-13 06:13 UTC, chenglu commented on src/docs/development/ui/animations/implicit-animations.md
> +## 无聊秀
保持英文现有的就行，就叫 Boring Show 就好啦。

2021-05-15 02:29 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +下列资源提供了许多在 Flutter 中学习使用隐式动画的方法
```suggestion
下列资源提供了许多在 Flutter 中学习使用隐式动画的方法。
```

2021-05-15 02:29 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +  Codelab uses 交互式示例和分布介绍来教你学会如何使用隐式动画。
uses 未修改。

2021-05-15 02:29 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +<br>[Flutter cookbook][] 中关于使用 [`AnimatedContainer`][] 隐式动画 widget 进行手把手诀窍指导。
可以优化一下。

2021-05-15 02:29 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +<br>所有隐式动画都扩展了 `ImplicitlyAnimatedWidget` class。
class 未修改。

2021-05-15 02:29 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +
```suggestion
```

2021-05-15 02:29 UTC, AlexV525 commented on src/docs/development/ui/animations/implicit-animations.md
> +观看《无聊秀》，跟随谷歌工程师用 Flutter 从零开始构建应用程序。
```suggestion
观看《The Boring Show》，跟随谷歌工程师用 Flutter 从零开始构建应用程序。
```

2021-05-15 04:52 UTC, AlexV525 approved these changes
LGTM

2021-05-15 08:05 UTC, merged