[翻译完成] src/docs/perf/deferred-components.md
cfug/flutter.cn pull request #882
Opened 2021-05-22 09:21 UTC by Nayuta403

2021-05-22 14:37 UTC, Vadaski requested changes
Good，还有一些小问题，空了看看昂～

2021-05-22 14:37 UTC, Vadaski commented on src/docs/perf/deferred-components.md
> +你可能需要单独支持 `SplitCompat` 并提供 `PlayStoreDynamicFeatureManager`。
「并提供」 => 「并手动并提供」

2021-05-22 14:37 UTC, Vadaski commented on src/docs/perf/deferred-components.md
> +    <p markdown="1">通过将 `deferred-components` 依赖添加到应用程序的 `pubspec.yaml` 中的 `flutter` 下，并选择延迟组件：</p>
「`flutter` 下」=>「`flutter` 条目下」

2021-05-22 14:37 UTC, Vadaski commented on src/docs/perf/deferred-components.md
> +  这可能导致意外和混乱的指令来解决故障。
这里我理解不是解决故障 ，而是出现需要解决的故障。待议

2021-05-22 14:37 UTC, Vadaski commented on src/docs/perf/deferred-components.md
> +  此标志用于不依赖验证程序检查的默认 Play-store-based 的自定义实现。
建议译为「此标志应当仅在不需要依赖验证程序检查的默认 Play-store-based 的自定义实现时使用。」

2021-05-22 14:37 UTC, Vadaski commented on src/docs/perf/deferred-components.md
> +验证程序会检测 `gen_snapshot` 生成所有新增、修改或者删除的加载单元。
「生成」=> 「生成的」

2021-05-22 14:37 UTC, Vadaski commented on src/docs/perf/deferred-components.md
> +当前生成的加载单元在 `<projectDirectory>/deferred_components_loading_units.yaml` 文件中记录。
当前生成的加载单元记录在 `<projectDirectory>/deferred_components_loading_units.yaml` 文件中。

2021-05-22 14:37 UTC, Vadaski commented on src/docs/perf/deferred-components.md
> +这个文件应该在源码管理中进行检查，以确保其他开发人员对加载单元所做的更改可被追踪。
这里我理解原文想表达的是 将这个文件加入版本管理，而不是检查

2021-05-24 01:02 UTC, CaiJingLong commented on src/docs/perf/deferred-components.md
> +因为除非检测到新的版本号，否则 Android 不会更新功能模块。
我感觉怪怪的，如果以中文来说可能正向表达更舒服一些，个人观点
```suggestion
因为只有检测到新的版本号， Android 才会去更新功能模块。
```

2021-05-24 12:49 UTC, Vadaski commented
ci 挂了一些，我看了下是 link 部分的，建议试下 update submodule 是否可以解决

2021-05-25 10:07 UTC, AlexV525 commented on src/docs/perf/deferred-components.md
> +
```suggestion
```

2021-05-25 10:07 UTC, AlexV525 commented on src/docs/perf/deferred-components.md
>    This feature is currently only available on Android,
```suggestion

  This feature is currently only available on Android,
```

2021-05-26 09:15 UTC, MeandNi approved these changes
LGTM modulo one nit below.

2021-05-26 09:48 UTC, Nayuta403 commented on src/docs/perf/deferred-components.md
> +这允许应用程序减少安装 apk 的大小，并在用户需要时下载功能和静态资源。
原文是 This allows apps，我感觉还是「允许」贴切一点吧，可以再看看

2021-05-26 09:55 UTC, MeandNi commented on src/docs/perf/deferred-components.md
> +这允许应用程序减少安装 apk 的大小，并在用户需要时下载功能和静态资源。
> 原文是 This allows apps，我感觉还是「允许」贴切一点吧，可以再看看

都可，但改完感觉更适合中文语境。

2021-05-26 10:01 UTC, chenglu commented on src/docs/perf/deferred-components.md
> +这允许应用程序减少安装 apk 的大小，并在用户需要时下载功能和静态资源。
Allow(s) you 的译法可参看 101.dev 的帖子 @MeandNi 
建议翻译为主动语态。https://101.dev/t/allow-s-you/49

2021-05-28 01:58 UTC, Nayuta403 commented on src/docs/perf/deferred-components.md
> +这允许应用程序减少安装 apk 的大小，并在用户需要时下载功能和静态资源。
@chenglu 
![image](https://user-images.githubusercontent.com/40540394/119918541-3d0c8980-bf9b-11eb-8bda-9f38b60ff9a7.png)  路哥链接挂了么

2021-05-28 02:08 UTC, AlexV525 commented on src/docs/perf/deferred-components.md
> +这允许应用程序减少安装 apk 的大小，并在用户需要时下载功能和静态资源。
allow you / enable you 是一个很常见的英文用法，我们不建议翻译为：
xxx(功能、特性、产品) 允许你 xxx (做某事、更方便的如何如何)

中文里建议翻译为主动语态：
我们可以使用 xxx(功能、特性、产品) 来 xxx (做某事、更方便的如何如何)。

比如：
:heavy_check_mark: 我们可以通过 Kotlin 内联类来创建包装类型。
:x: Kotlin 内联类允许我们创建包装类型。

2021-05-29 09:25 UTC, AlexV525 commented on src/docs/perf/deferred-components.md
>    You can opt out of building deferred components
```suggestion

  You can opt out of building deferred components
```

2021-05-29 09:25 UTC, AlexV525 commented on src/docs/perf/deferred-components.md
>    You can opt to have the tool attempt to build your
```suggestion

  You can opt to have the tool attempt to build your
```

2021-05-29 09:25 UTC, AlexV525 commented on src/docs/perf/deferred-components.md
> +再次运行 `build-apks` 之前，请删除已存在的 app.apks 文件：
```suggestion
再次运行 `build-apks` 之前，请删除已存在的 .apks 文件：
```

2021-05-29 09:25 UTC, AlexV525 commented on src/docs/perf/deferred-components.md
> +因为只有检测到新的版本号， Android 才会去更新功能模块。
```suggestion
因为只有检测到新的版本号，Android 才会去更新功能模块。
```

2021-05-29 15:15 UTC, Vadaski approved these changes

2021-05-29 15:16 UTC, Vadaski commented
LGTM

2021-05-29 15:16 UTC, merged