[翻译完成] src/docs/development/data-and-backend/google-apis.md
cfug/flutter.cn pull request #889
Opened 2021-06-01 09:19 UTC by yumi0629

[翻译完成] src/docs/development/data-and-backend/google-apis.md
fix #870

2021-06-01 10:12 UTC, MeandNi commented on src/docs/development/data-and-backend/google-apis.md
> +## 2. 启用API
```suggestion
## 2. 启用 API
```

2021-06-01 12:39 UTC, chenglu commented on src/docs/development/data-and-backend/google-apis.md
> +[Google APIs package]({{site.pub-pkg}}/googleapis) 暴露了许多你可以从 Dart 项目中使用的 Google 服务。
```suggestion
[Google APIs package]({{site.pub-pkg}}/googleapis) 提供了许多你可以从 Dart 项目中使用的 Google 服务。
```

2021-06-01 12:54 UTC, Nayuta403 reviewed
辛苦啦~

2021-06-01 12:54 UTC, Nayuta403 commented on src/docs/development/data-and-backend/google-apis.md
> +——采用 `name.version` 的形式。让我们以 [`youtube.v3`]({{site.pub-api}}/googleapis/latest/youtube.v3/youtube.v3-library.html) 为例。
```suggestion
文档 [package:googleapis]({{site.pub-api}}/googleapis) 采用 `name.version` 的形式，列举了每一个可以单独作为 Dart 库的 API 
。一起看看 [`youtube.v3`]({{site.pub-api}}/googleapis/latest/youtube.v3/youtube.v3-library.html) 这个例子。
```

2021-06-01 12:54 UTC, Nayuta403 commented on src/docs/development/data-and-backend/google-apis.md
> +使用 Google API，你必须有一个 Google 账户和一个 Google 项目。你还需要开启所需的 API。
```suggestion
使用 Google API，你必须有一个 Google 账户和一个 Google 项目。你还需要启用所需的 API 服务。
```
我看 Google 的网站里面用的是「启用」，这里 API 我觉得是指的这项服务

2021-06-01 12:54 UTC, Nayuta403 commented on src/docs/development/data-and-backend/google-apis.md
> +  这个 [`extension_google_sign_in_as_googleapis_auth` 例子]({{site.pub-pkg}}/extension_google_sign_in_as_googleapis_auth/example)
```suggestion
  这个例子 [`extension_google_sign_in_as_googleapis_auth` ]({{site.pub-pkg}}/extension_google_sign_in_as_googleapis_auth/example) 
```
[]里面的内容一半翻译一半不翻感觉怪怪的，可以再看看

2021-06-01 12:54 UTC, Nayuta403 commented on src/docs/development/data-and-backend/google-apis.md
> +在这个例子中，你开启了 [YouTube Data API v3](https://console.cloud.google.com/apis/api/youtube.googleapis.com)。
```suggestion
在这个例子中，你启用了 [YouTube Data API v3](https://console.cloud.google.com/apis/api/youtube.googleapis.com) 服务。
```
同上

2021-06-01 13:00 UTC, chenglu commented on src/docs/development/data-and-backend/google-apis.md
> +在这个例子中，你开启了 [YouTube Data API v3](https://console.cloud.google.com/apis/api/youtube.googleapis.com)。
you'd enable 应该是 you would enable，可能翻译的更书面语一些，比如：
在本样例中，你将需要启用 xxxx 服务。

2021-06-01 13:01 UTC, chenglu commented on src/docs/development/data-and-backend/google-apis.md
> +这个 [`Client`]({{site.pub-api}}/http/latest/http/Client-class.html) 实例
```suggestion
[`Client`]({{site.pub-api}}/http/latest/http/Client-class.html) 实例
```
「这个」翻译的有点多余。

2021-06-01 13:03 UTC, chenglu requested changes
建议根据大家提出的修改建议进行适当的修改。

2021-06-02 01:31 UTC, yumi0629 commented on src/docs/development/data-and-backend/google-apis.md
> +  这个 [`extension_google_sign_in_as_googleapis_auth` 例子]({{site.pub-pkg}}/extension_google_sign_in_as_googleapis_auth/example)
```suggestion
  示例 [`extension_google_sign_in_as_googleapis_auth`]({{site.pub-pkg}}/extension_google_sign_in_as_googleapis_auth/example) 
  是本页面所述概念的一个可行的实现。
```
感觉“这个”也是多余的，可以不加。“例子”改成“示例”、“样例”是不是更加正式一点？

2021-06-07 03:20 UTC, chenglu approved these changes

2021-06-07 03:20 UTC, merged