[完成翻译] src/docs/development/ui/layout/building-adaptive-apps.md
cfug/flutter.cn pull request #904
Opened 2021-06-22 10:28 UTC by AlexV525

2021-06-22 12:56 UTC, Nayuta403 reviewed
姜还是 A 的辣啊

2021-06-22 12:56 UTC, Nayuta403 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +在构建多平台的应用时，首要考虑的事是如何针对不同设备大小进行尺寸适配。
```suggestion
在构建多平台的应用时，首要考虑的是如何针对不同大小的设备进行尺寸适配。
```

2021-08-03 09:59 UTC, chenglu commented
祝贺，完成了一篇，这么长长长长长长长长的文章。

2021-08-04 04:09 UTC, Nayuta403 reviewed
鸡蛋里面挑骨头了，A少厉害

2021-08-04 04:09 UTC, Nayuta403 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +无单位的设计让它可以处理通用情况，能在大部分的场景下使用。
```suggestion
我们可以看到，`VisualDensity` 是没有单位的，
所以在不同的视图上可能有不同的含义。
在以上的例子中，1 个单位的密度等同于 6 个逻辑像素。
具体的处理完全由你的视图自行决定。
无单位的设计让它可以处理通用情况，
能在大部分的场景下使用。
```

2021-08-04 04:09 UTC, Nayuta403 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +你可以使用代码进行更细化的控制、计算尺寸、切换 widgets
```suggestion
如果你需要的不仅是密度的变化，并且没有找到一个满足需求的 widget，
那么你可以使用代码进行更细化的控制、计算尺寸、切换 widgets，
```
不仅xx  同时xx 是不是改成 不仅xx 而且xx 通顺一点
`what you need` 感觉和 `使用场景契合`  意思不太相符

2021-08-04 10:29 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +所有的自定义组件都会联系在一起，使整个应用平滑过渡。
> 所有的自定义组件和内置组件都会联系在一起

改成「所有的组件」？

2021-08-04 10:31 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +你可以使用代码进行更细化的控制、计算尺寸、切换 widgets
outdated 了

2021-08-05 02:43 UTC, Nayuta403 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +所有的自定义组件都会联系在一起，使整个应用平滑过渡。
原文应该也是这个意思

2021-08-05 15:16 UTC, Nayuta403 approved these changes
LGTM~

2021-08-10 16:28 UTC, Vadaski reviewed
review：322
翻译得相当赞，一些小建议供 A 少参考

2021-08-10 16:28 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +**单子级**
这里 我个人更倾向于不译，因为「单子级」对于开发者来说相比 Single child 又增加了一层理解的映射，本文受众对于这个单词应该还是比较熟悉的～ 待议

2021-08-10 16:28 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +  可使用 -1 至 1 的双精度值在垂直和水平方向上进行对齐。
双精度 => double ，会是开发者更加熟悉的词

2021-08-10 16:28 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +
如果我们要使用 Single Child 这样的说法，上面的都需要替换一下（看咱们最后咋定了）

2021-08-10 16:28 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +  [`Flow`][]&mdash;&mdash;与 `CustomMultiChildLayout` 类似但更高效。
[`Flow`][]&mdash;&mdash; 是一种相对于 `CustomMultiChildLayout` 来说更加高效的布局方式

读者对于 高效 的感知会不会更强一点

2021-08-10 16:28 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +  [`Table`][]&mdash;&mdash;基于基础的表格布局算法，将子级组合为多列和多行。
[`Table`][]&mdash;&mdash; 使用了经典的表格布局算法，能够组合多个 row 和 column

供参考～

2021-08-10 16:28 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +比如在可触控设备上放大按钮（更容易点击）。
放大按钮 可能听上去有点像一个名词 => 「放大一个按钮（让它更容易被点击）」供参考

2021-08-10 16:28 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +支持它的 `MaterialComponents` 会以动画过渡改变其自身的密度。
`MaterialComponents` that support it animate their densities to match.
这里我理解是 「`MaterialComponents` 都支持了密度过渡动画」

2021-08-10 16:28 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +你可以通过调整密度轻松地调整你的 UI：
这两句我觉得是不是合并成一句中文读出来好一点？
「水平和垂直方向的密度默认都为 0.0，你可以将它设置为任意的正负值，也可以通过改变视觉密度轻松地调整你的 UI：
 」

2021-08-11 14:34 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +  可使用 -1 至 1 的双精度值在垂直和水平方向上进行对齐。
不如直接省略双精度？「可使用 -1 至 1 之间的任意值在垂直和水平方向上进行对齐。」

2021-08-11 16:09 UTC, Vadaski reviewed
A 少辛苦啦，一点建议供参考～

2021-08-11 16:09 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +要想在全局监听中判断组合按键，你可以使用 `RawKeyboard.instance.keysPressed` map。
这里的 map 指的是什么，我没有太理解，感觉好像不是指的数据结构那个 map

2021-08-11 16:09 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +或关联的 widget 从视图中隐藏时，监听通常需要禁用。
通常需要禁用监听器

2021-08-11 16:09 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +  让用户更直接地完成操作，而无需过多地思考，从而提高生产力，减少其中的顿挫感。
这段翻译的很赞

2021-08-11 16:09 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +在当代桌面应用中，经常会有定制应用窗口的标题栏、添加 Logo 或者其他控制的需求，
「当代」 => 「现代」
改不改无关紧要，只是我的强迫症>_<

2021-08-11 16:10 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +最简单的代码控制布局方式是基于屏幕尺寸来定义断点。
后面还有好几处～

2021-08-12 01:32 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +要想在全局监听中判断组合按键，你可以使用 `RawKeyboard.instance.keysPressed` map。
`RawKeyboard.instance.keysPressed` 本身是个 Map

2021-08-12 02:12 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +例如，你可以判断用户是否使用手持设备，来切换垂直或水平的布局：
这里应该是主要想说明：手持设备有更小的宽度，平板/桌面设备有更大的宽度，所以才切换水平和垂直吧

2021-08-12 02:13 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +#### 细化设备
那应该叫「设备细化」/「设备细分」？

2021-08-17 13:38 UTC, MeandNi requested changes

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +而由于判断时条件进行了阻断，在 Web 平台上永远不会调用 `Platform` API。
```suggestion
所以在上面的代码中，会首先判断是否在 Web 平台，
基于这个条件，在 Web 平台上永远不会调用 `Platform` API。
```

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +常见的设计类型里，有一些分类可以以这样的方式进行组织：
```suggestion
常见的设计类型里，如下这些类别可以以这样的方式进行组织：
```

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +完善了触摸界面后，你可以调整鼠标用户的视觉密度，然后对所有的输入设备进行分层。
```suggestion
完善了触摸界面后，你可以调整面向鼠标用户的视觉密度，然后对所有的输入设备进行分层。
```

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +特别是有动效和视觉障碍的用户，基本依赖于键盘导航。
```suggestion
特别是对有动效和视觉障碍的用户，他们几乎完全依赖于键盘导航。
```

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +用户可能会在 `TextField` 输入内容时受到影响。
```suggestion
使用静态的监听时有一件值得注意的事情，当用户在输入框中输入内容，
或关联的 widget 从视图中隐藏时，通常需要禁用监听。
与 `Shortcuts` 和 `RawKeyboardListener` 不同，你需要自己对它们进行管理。
当你在为 `Delete` 键构建一个删除或退格行为的监听时，需要尤其注意，
因为用户可能会在 `TextField` 中输入内容时受到影响。
```

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +在考虑时，你要将已经实现的功能的限制抛诸脑后，仅针对理想的用户体验进行逆向思考。
这里我理解是「能不能实现这个功能的限制抛诸脑后」 
```suggestion
试着将当前能否实现的限制抛诸脑后，仅针对理想的用户体验进行逆向思考。
```

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +一位支持 Linux 和 Web，一位支持 Mac 和 iOS。
这里翻译为「负责人」是否好点，下同。
```suggestion
最好为每一种适配平台指定一位负责人。
理想情况下，负责人以他们熟悉的平台为主，提供他们对平台特有的看法和意见。
若想减少人员，兼顾角色，可以安排一位支持 Windows 和 Android，
一位支持 Linux 和 Web，一位支持 Mac 和 iOS。
```

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +倡议者应该以挑剔的角度对平台实现进行把关。一个非常简单的例子是在对话框里，
```suggestion
负责人应该以挑剔的角度对平台实现进行把关。一个非常简单的例子是在对话框里，
```

2021-08-17 13:38 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +我们希望这个功能最终能合并到 SDK 中。
有没有兴趣提个 PR 😂。

2021-08-17 15:58 UTC, Vadaski commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +#### 细化设备
同意

2021-08-17 16:33 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +在考虑时，你要将已经实现的功能的限制抛诸脑后，仅针对理想的用户体验进行逆向思考。
这么理解也很合理~

2021-08-17 16:35 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +  **重要**：倡导者不需要是开发者或者一直在开发的团队成员，
```suggestion
  **重要**：负责人不需要是开发者或者一直在开发的团队成员，
```

2021-08-18 04:36 UTC, MeandNi approved these changes
LGTM with a nit.

2021-08-18 04:36 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +一般来说，触屏用户希望看到拖动的手柄，以区分拖动和滚动的范围，
```suggestion
一般来说，触屏用户希望看到可拖动的手柄，以区分拖动和滚动的范围，
```

2021-08-18 06:06 UTC, AlexV525 commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +我们希望这个功能最终能合并到 SDK 中。
不是一个已经存在的功能吗~

2021-08-18 06:56 UTC, MeandNi commented on src/docs/development/ui/layout/building-adaptive-apps.md
> +我们希望这个功能最终能合并到 SDK 中。
看这意思是目前这个功能是使用插件实现的，还没合到 SDK 里面。

2021-08-18 07:26 UTC, merged