[完成翻译] src/docs/deploument/macos.md
cfug/flutter.cn pull request #915
Opened 2021-07-09 03:57 UTC by Nayuta403

#899

2021-07-09 08:22 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +1. 点击 **我的应用程序** 页面左上角的 **+**，然后选择 **新建应用程序**。
这些内容在 Xcode 中应该都是以英文展示的，可以按照 `英文（中文）` 的格式统一，下同

2021-07-09 08:22 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +`version: 1.0.0+1`
```suggestion
```

2021-07-09 08:22 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +开发阶段，你已经在 _debug_ 模式下完成应用的构建、调试和测试。
生疏了？

```suggestion
在开发时，你已经完成了在 **debug** 模式下的应用构建、调试和测试。
```

2021-07-09 08:22 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +请参阅 [distribution guide][distributionguide_macos]，
```suggestion
请参阅 [分发指南][distributionguide_macos]，
```

2021-07-10 05:11 UTC, Nayuta403 commented on src/docs/deployment/macos.md
> +开发阶段，你已经在 _debug_ 模式下完成应用的构建、调试和测试。
第一遍是这么翻的，后来多读几遍感觉怪怪的🤔🤔🤔 你细品

2021-07-10 05:11 UTC, Nayuta403 commented on src/docs/deployment/macos.md
> +1. 点击 **我的应用程序** 页面左上角的 **+**，然后选择 **新建应用程序**。
ok

2021-07-10 05:43 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +开发阶段，你已经在 _debug_ 模式下完成应用的构建、调试和测试。
主要是英文强调的格式 用的是 `**`

2021-07-10 13:43 UTC, Nayuta403 commented on src/docs/deployment/macos.md
> +开发阶段，你已经在 _debug_ 模式下完成应用的构建、调试和测试。
嗷嗷 😏😏

2021-07-11 11:34 UTC, AlexV525 requested changes

2021-07-11 11:34 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +1. 在表单中填写应用程序详细信息。
所有的列表项，都需要换行，且不需要索引

2021-07-11 11:34 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +  如果需要，请选择 **添加账户...**，然后更新此设置。
所有的 Xcode 内部英文项翻译需要回滚，或者以括号形式存在

2021-07-11 13:08 UTC, Nayuta403 commented on src/docs/deployment/macos.md
> +  如果需要，请选择 **添加账户...**，然后更新此设置。
嗯嗯 明儿上班弄🤨

2021-07-12 04:57 UTC, chenglu commented on src/docs/deployment/macos.md
>     则其状态为 **1.0 准备提交**。填写所有必填字段。
```suggestion
   则其状态为 **1.0 准备提交**。填写所有必填字段。  
   
```

2021-07-12 04:58 UTC, AlexV525 commented on src/docs/deployment/macos.md
>     则其状态为 **1.0 准备提交**。填写所有必填字段。
@Nayuta403 懈怠了呀~

2021-07-12 06:54 UTC, Nayuta403 commented on src/docs/deployment/macos.md
>     则其状态为 **1.0 准备提交**。填写所有必填字段。
😏😏 over

2021-07-13 02:32 UTC, chenglu approved these changes

2021-07-13 07:56 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +请参阅 [App Store Connect][appstoreconnect_guide]。
原文有，虽不在链接里，但是这里漏了

```suggestion
请参阅 [App Store Connect 指南][appstoreconnect_guide]。
```

2021-07-13 07:56 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +开发阶段，你已经在 _debug_ 模式下完成应用的构建、调试和测试。
这部分尚未更新

2021-07-13 07:56 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +   在标识部分，将 **Build identifier（构建标识）** 更新为在 App Store Connect 上可以跟踪此生成的唯一生成串。
```suggestion
   在标识部分，将 **Build identifier（构建标识）**
   更新为在 App Store Connect 上可以跟踪此生成的唯一生成串。
```

2021-07-13 07:56 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +打开 Xcode 并选择 **项目 > 存档**。运行 `flutter build macos` 生成构建存档。
再检查下有没有没有调整的英文选项

2021-07-13 07:56 UTC, AlexV525 commented on src/docs/deployment/macos.md
> +你可以在 [App Store Connect][appstoreconnect_login] 上的应用程序详细信息页的活动标签下查看构建状态。
```suggestion
你可以在 [App Store Connect][appstoreconnect_login]
上的应用程序详细信息页的活动标签下查看构建状态。
```

2021-07-14 02:15 UTC, Nayuta403 commented on src/docs/deployment/macos.md
> +打开 Xcode 并选择 **项目 > 存档**。运行 `flutter build macos` 生成构建存档。
行，有时间改了 我再 review 一遍

2021-07-18 07:40 UTC, Nayuta403 commented on src/docs/deployment/macos.md
> +注册应用程序包括两个步骤：注册唯一的 Bundle ID，
```suggestion
注册应用程序包括两个步骤：注册一个唯一的 Bundle ID，
```

2021-07-18 07:40 UTC, Nayuta403 commented on src/docs/deployment/macos.md
> +   在 App Store Connect 登录页上，点击我的应用。
```suggestion
   在 App Store Connect 登录页上，点击 **我的应用程序**。
```

2021-07-18 07:40 UTC, Nayuta403 commented on src/docs/deployment/macos.md
> +   点击 **我的应用程序** 页面左上角的 **+**，然后选择 **新建应用程序**。
```suggestion
   点击我的应用程序页面左上角的 **+**，然后选择 **新建应用程序**。
```

2021-07-20 12:05 UTC, AlexV525 approved these changes
👍

2021-07-20 12:05 UTC, merged